// 레벨 → 스테이지 → 단어 데이터.
// 단어 형식: [영단어, 품사(n/v/adj/adv), 뜻, 예문(대상 단어를 *...*로 감쌈), 예문 해석]
// 예문 속 *...*는 영단어와 똑같은 형태여야 합니다(빈칸 퀴즈가 이 표시를 이용). `node tests/test.mjs`로 검증됩니다.

const RAW = [
  {
    id: 1, name: '새싹', icon: '🌱', desc: '초등~중1 기초',
    stages: [
      { name: '일상 동사', words: [
        ['wake up', 'v', '일어나다', 'I *wake up* at seven every day.', '나는 매일 7시에 일어난다.'],
        ['borrow', 'v', '빌리다', 'Can I *borrow* your pen?', '펜 좀 빌려도 될까?'],
        ['carry', 'v', '나르다, 들고 다니다', 'Please *carry* this bag for me.', '이 가방 좀 들어 주세요.'],
        ['cook', 'v', '요리하다', 'My dad likes to *cook* on weekends.', '아빠는 주말에 요리하는 것을 좋아하신다.'],
        ['wash', 'v', '씻다', 'You should *wash* your hands before eating.', '먹기 전에 손을 씻어야 한다.'],
        ['leave', 'v', '떠나다', 'We *leave* for school at eight.', '우리는 8시에 학교로 출발한다.'],
        ['count', 'v', '세다', "Let's *count* from one to ten.", '1부터 10까지 세어 보자.'],
        ['wait', 'v', '기다리다', 'Please *wait* here for a moment.', '여기서 잠시만 기다려 주세요.'],
      ] },
      { name: '학교와 사물', words: [
        ['lesson', 'n', '수업, 교훈', "Today's *lesson* is about animals.", '오늘 수업은 동물에 관한 것이다.'],
        ['homework', 'n', '숙제', 'I finished my *homework* early.', '나는 숙제를 일찍 끝냈다.'],
        ['library', 'n', '도서관', 'She reads books in the *library*.', '그녀는 도서관에서 책을 읽는다.'],
        ['notebook', 'n', '공책', 'Write it in your *notebook*.', '그것을 공책에 적어라.'],
        ['subject', 'n', '과목, 주제', 'Math is my favorite *subject*.', '수학은 내가 가장 좋아하는 과목이다.'],
        ['desk', 'n', '책상', 'The books are on the *desk*.', '책들이 책상 위에 있다.'],
        ['exam', 'n', '시험', 'I have an *exam* tomorrow.', '나는 내일 시험이 있다.'],
        ['classmate', 'n', '반 친구', 'My *classmate* helped me with the project.', '반 친구가 프로젝트를 도와주었다.'],
      ] },
      { name: '음식과 장소', words: [
        ['delicious', 'adj', '맛있는', 'This soup is *delicious*.', '이 수프는 맛있다.'],
        ['hungry', 'adj', '배고픈', 'I am so *hungry* right now.', '나는 지금 너무 배가 고프다.'],
        ['bakery', 'n', '빵집', 'The *bakery* opens at six.', '그 빵집은 6시에 문을 연다.'],
        ['market', 'n', '시장', 'We buy fresh fruit at the *market*.', '우리는 시장에서 신선한 과일을 산다.'],
        ['restaurant', 'n', '식당', 'They ate dinner at a new *restaurant*.', '그들은 새 식당에서 저녁을 먹었다.'],
        ['drink', 'v', '마시다', 'You should *drink* more water.', '너는 물을 더 마셔야 한다.'],
        ['hospital', 'n', '병원', 'My aunt works at the *hospital*.', '이모는 병원에서 일하신다.'],
        ['station', 'n', '역', 'Meet me at the train *station*.', '기차역에서 만나자.'],
      ] },
      { name: '감정과 상태', words: [
        ['angry', 'adj', '화난', 'He was *angry* about the mistake.', '그는 그 실수에 화가 났다.'],
        ['proud', 'adj', '자랑스러운', 'I am *proud* of you.', '나는 네가 자랑스럽다.'],
        ['nervous', 'adj', '긴장한', 'She felt *nervous* before the speech.', '그녀는 연설 전에 긴장했다.'],
        ['lonely', 'adj', '외로운', 'He felt *lonely* in the new city.', '그는 새 도시에서 외로움을 느꼈다.'],
        ['surprised', 'adj', '놀란', 'We were *surprised* by the news.', '우리는 그 소식에 놀랐다.'],
        ['tired', 'adj', '피곤한', 'I was too *tired* to study.', '나는 너무 피곤해서 공부할 수 없었다.'],
        ['excited', 'adj', '신이 난', 'The kids are *excited* about the trip.', '아이들은 여행에 신이 나 있다.'],
        ['worry', 'v', '걱정하다', "Don't *worry* about the test.", '시험은 걱정하지 마.'],
      ] },
    ],
  },
  {
    id: 2, name: '새잎', icon: '🌿', desc: '중등 필수',
    stages: [
      { name: '생활 동사', words: [
        ['invite', 'v', '초대하다', 'I want to *invite* you to my party.', '너를 내 파티에 초대하고 싶어.'],
        ['improve', 'v', '향상시키다, 개선하다', 'Reading helps you *improve* your English.', '독서는 영어 실력을 향상시키는 데 도움이 된다.'],
        ['share', 'v', '나누다, 공유하다', 'Please *share* your ideas with the group.', '여러분의 생각을 모둠과 공유해 주세요.'],
        ['decide', 'v', '결정하다', 'It is hard to *decide* what to eat.', '무엇을 먹을지 결정하기가 어렵다.'],
        ['prepare', 'v', '준비하다', 'We need to *prepare* for the trip.', '우리는 여행을 준비해야 한다.'],
        ['repeat', 'v', '반복하다', 'Could you *repeat* that, please?', '다시 한번 말씀해 주시겠어요?'],
        ['mention', 'v', '언급하다', 'She did not *mention* the problem.', '그녀는 그 문제를 언급하지 않았다.'],
        ['protect', 'v', '보호하다', 'We must *protect* the environment.', '우리는 환경을 보호해야 한다.'],
      ] },
      { name: '사람과 관계', words: [
        ['neighbor', 'n', '이웃', 'Our *neighbor* is very kind.', '우리 이웃은 아주 친절하다.'],
        ['relative', 'n', '친척', 'I visit my *relative* in Busan every summer.', '나는 매년 여름 부산에 사는 친척을 방문한다.'],
        ['stranger', 'n', '낯선 사람', "Don't talk to a *stranger* online.", '온라인에서 낯선 사람과 이야기하지 마라.'],
        ['customer', 'n', '손님, 고객', 'The *customer* asked for a refund.', '그 고객은 환불을 요청했다.'],
        ['teenager', 'n', '십대', 'My brother is a *teenager* now.', '내 형은 이제 십대이다.'],
        ['citizen', 'n', '시민', 'Every *citizen* has the right to vote.', '모든 시민은 투표할 권리가 있다.'],
        ['volunteer', 'n', '자원봉사자', 'She works as a *volunteer* at the shelter.', '그녀는 보호소에서 자원봉사자로 일한다.'],
        ['partner', 'n', '짝, 파트너', 'Find a *partner* and practice speaking.', '짝을 찾아서 말하기를 연습해라.'],
      ] },
      { name: '자연과 날씨', words: [
        ['weather', 'n', '날씨', 'The *weather* is nice today.', '오늘은 날씨가 좋다.'],
        ['temperature', 'n', '온도, 기온', 'The *temperature* dropped at night.', '밤에 기온이 떨어졌다.'],
        ['storm', 'n', '폭풍', 'A big *storm* is coming tonight.', '오늘 밤 큰 폭풍이 온다.'],
        ['forest', 'n', '숲', 'We walked through the *forest*.', '우리는 숲속을 걸었다.'],
        ['island', 'n', '섬', 'They live on a small *island*.', '그들은 작은 섬에 산다.'],
        ['valley', 'n', '계곡, 골짜기', 'A river runs through the *valley*.', '강이 계곡을 가로질러 흐른다.'],
        ['flood', 'n', '홍수', 'The *flood* damaged many houses.', '홍수로 많은 집이 피해를 입었다.'],
        ['environment', 'n', '환경', 'Plastic is bad for the *environment*.', '플라스틱은 환경에 나쁘다.'],
      ] },
      { name: '형용사 모음', words: [
        ['ordinary', 'adj', '평범한', 'It was an *ordinary* day at school.', '학교에서의 평범한 하루였다.'],
        ['dangerous', 'adj', '위험한', 'Swimming here is *dangerous*.', '여기서 수영하는 것은 위험하다.'],
        ['familiar', 'adj', '익숙한', 'Her face looks *familiar*.', '그녀의 얼굴이 낯익다.'],
        ['terrible', 'adj', '끔찍한', 'I had a *terrible* headache.', '나는 끔찍한 두통이 있었다.'],
        ['honest', 'adj', '정직한', 'He is an *honest* person.', '그는 정직한 사람이다.'],
        ['flexible', 'adj', '유연한', 'My schedule is *flexible* this week.', '이번 주 내 일정은 유연하다.'],
        ['valuable', 'adj', '소중한, 가치 있는', 'Time is *valuable*.', '시간은 소중하다.'],
        ['cheerful', 'adj', '쾌활한', 'She is always *cheerful*.', '그녀는 늘 쾌활하다.'],
      ] },
    ],
  },
  {
    id: 3, name: '나무', icon: '🌳', desc: '고등 기초',
    stages: [
      { name: '학습과 사고', words: [
        ['concentrate', 'v', '집중하다', 'It is hard to *concentrate* in a noisy room.', '시끄러운 방에서는 집중하기 어렵다.'],
        ['memorize', 'v', '암기하다', 'I *memorize* ten words every day.', '나는 매일 단어 열 개를 암기한다.'],
        ['analyze', 'v', '분석하다', 'Scientists *analyze* the data carefully.', '과학자들은 자료를 꼼꼼히 분석한다.'],
        ['imagine', 'v', '상상하다', 'Can you *imagine* life without phones?', '휴대폰 없는 삶을 상상할 수 있니?'],
        ['curious', 'adj', '호기심 많은', 'Children are *curious* about everything.', '아이들은 모든 것에 호기심이 많다.'],
        ['assume', 'v', '가정하다, 추정하다', "Don't *assume* that everyone agrees.", '모두가 동의한다고 가정하지 마라.'],
        ['evidence', 'n', '증거', 'There is no *evidence* for that claim.', '그 주장에는 증거가 없다.'],
        ['conclude', 'v', '결론짓다', 'We can *conclude* that the plan works.', '우리는 그 계획이 효과가 있다고 결론지을 수 있다.'],
      ] },
      { name: '사회와 사건', words: [
        ['government', 'n', '정부', 'The *government* announced a new policy.', '정부는 새로운 정책을 발표했다.'],
        ['society', 'n', '사회', 'Technology has changed modern *society*.', '기술은 현대 사회를 변화시켰다.'],
        ['economy', 'n', '경제', 'The *economy* is growing slowly.', '경제가 느리게 성장하고 있다.'],
        ['crisis', 'n', '위기', 'The country faced a serious *crisis*.', '그 나라는 심각한 위기에 직면했다.'],
        ['democracy', 'n', '민주주의', 'Free speech is important in a *democracy*.', '민주주의에서는 표현의 자유가 중요하다.'],
        ['tradition', 'n', '전통', 'This festival is an old *tradition*.', '이 축제는 오래된 전통이다.'],
        ['opportunity', 'n', '기회', 'This job is a great *opportunity*.', '이 일자리는 좋은 기회이다.'],
        ['community', 'n', '지역 사회', 'The *community* raised money for the school.', '지역 사회가 학교를 위해 돈을 모았다.'],
      ] },
      { name: '변화와 결과', words: [
        ['increase', 'v', '증가하다', 'Prices *increase* every year.', '물가는 해마다 오른다.'],
        ['reduce', 'v', '줄이다', 'We should *reduce* waste.', '우리는 쓰레기를 줄여야 한다.'],
        ['achieve', 'v', '이루다, 달성하다', 'She worked hard to *achieve* her goal.', '그녀는 목표를 이루기 위해 열심히 노력했다.'],
        ['affect', 'v', '영향을 미치다', 'Sleep can *affect* your mood.', '수면은 기분에 영향을 미칠 수 있다.'],
        ['consequence', 'n', '결과', 'Every choice has a *consequence*.', '모든 선택에는 결과가 따른다.'],
        ['establish', 'v', '설립하다, 확립하다', 'They plan to *establish* a new school.', '그들은 새 학교를 설립할 계획이다.'],
        ['gradually', 'adv', '서서히', 'The weather *gradually* got warmer.', '날씨가 서서히 따뜻해졌다.'],
        ['threaten', 'v', '위협하다', 'Pollution can *threaten* wildlife.', '오염은 야생동물을 위협할 수 있다.'],
      ] },
      { name: '성격과 태도', words: [
        ['generous', 'adj', '너그러운, 후한', 'He is *generous* with his time.', '그는 자기 시간을 아낌없이 내준다.'],
        ['stubborn', 'adj', '고집 센', 'My little brother is very *stubborn*.', '내 동생은 매우 고집이 세다.'],
        ['reliable', 'adj', '믿을 수 있는', 'She is a *reliable* friend.', '그녀는 믿을 수 있는 친구이다.'],
        ['selfish', 'adj', '이기적인', 'It was *selfish* to take all the cake.', '케이크를 다 가져간 것은 이기적이었다.'],
        ['confident', 'adj', '자신감 있는', 'Be *confident* and speak clearly.', '자신감을 갖고 또렷하게 말해라.'],
        ['humble', 'adj', '겸손한', 'Despite his fame, he stays *humble*.', '유명하지만 그는 겸손함을 유지한다.'],
        ['cautious', 'adj', '조심스러운', 'Be *cautious* when you cross the road.', '길을 건널 때는 조심해라.'],
        ['ambitious', 'adj', '야심 찬', 'She is an *ambitious* young leader.', '그녀는 야심 찬 젊은 지도자이다.'],
      ] },
      { name: '과학과 기술', words: [
        ['experiment', 'n', '실험', 'Scientists conducted an *experiment* to test the theory.', '과학자들은 그 이론을 검증하기 위해 실험을 했다.'],
        ['invent', 'v', '발명하다', 'He wants to *invent* a new machine.', '그는 새로운 기계를 발명하고 싶어 한다.'],
        ['technology', 'n', '기술', 'New *technology* makes life easier.', '새로운 기술은 삶을 더 편리하게 만든다.'],
        ['device', 'n', '기기, 장치', 'This *device* can measure your heart rate.', '이 기기는 심박수를 측정할 수 있다.'],
        ['discover', 'v', '발견하다', 'Scientists *discover* new species every year.', '과학자들은 매년 새로운 종을 발견한다.'],
        ['laboratory', 'n', '실험실', 'She works in a chemistry *laboratory*.', '그녀는 화학 실험실에서 일한다.'],
        ['artificial', 'adj', '인공의', 'The lake has *artificial* lighting at night.', '그 호수는 밤에 인공 조명이 있다.'],
        ['innovative', 'adj', '혁신적인', 'The company released an *innovative* product.', '그 회사는 혁신적인 제품을 출시했다.'],
      ] },
      { name: '역사와 문화', words: [
        ['ancient', 'adj', '고대의', 'They found *ancient* coins in the field.', '그들은 들판에서 고대 동전을 발견했다.'],
        ['century', 'n', '세기', 'This castle was built in the 14th *century*.', '이 성은 14세기에 지어졌다.'],
        ['civilization', 'n', '문명', 'The Nile supported an early *civilization*.', '나일강은 초기 문명을 지탱했다.'],
        ['heritage', 'n', '유산, 문화재', 'This temple is a cultural *heritage* site.', '이 사원은 문화유산 지역이다.'],
        ['ritual', 'n', '의식, 의례', 'The tribe performs a special *ritual* every spring.', '그 부족은 매년 봄 특별한 의식을 치른다.'],
        ['myth', 'n', '신화', 'Greek *myth* tells the story of gods and heroes.', '그리스 신화는 신과 영웅들의 이야기를 전한다.'],
        ['explore', 'v', '탐험하다', 'Early sailors wanted to *explore* unknown oceans.', '초기 선원들은 미지의 바다를 탐험하고 싶어 했다.'],
        ['legacy', 'n', '업적, 유산', 'He left a great *legacy* for future generations.', '그는 후대를 위해 위대한 업적을 남겼다.'],
      ] },
      { name: '건강과 의학', words: [
        ['symptom', 'n', '증상', 'A high fever is a common *symptom* of flu.', '고열은 독감의 흔한 증상이다.'],
        ['treatment', 'n', '치료', 'The *treatment* lasted six weeks.', '그 치료는 6주 동안 계속되었다.'],
        ['diagnose', 'v', '진단하다', 'The doctor will *diagnose* the illness tomorrow.', '의사는 내일 그 병을 진단할 것이다.'],
        ['recover', 'v', '회복하다', 'It took months to *recover* from the surgery.', '수술에서 회복하는 데 몇 달이 걸렸다.'],
        ['nutrition', 'n', '영양', 'Good *nutrition* keeps your body strong.', '좋은 영양은 몸을 튼튼하게 유지해 준다.'],
        ['exhausted', 'adj', '기진맥진한', 'She felt *exhausted* after the marathon.', '그녀는 마라톤 후에 기진맥진했다.'],
        ['chronic', 'adj', '만성의', 'He suffers from a *chronic* back pain.', '그는 만성 요통을 앓고 있다.'],
        ['immune', 'adj', '면역의', 'Vitamin C can boost your *immune* system.', '비타민 C는 면역 체계를 강화할 수 있다.'],
      ] },
      { name: '법과 규범', words: [
        ['law', 'n', '법', 'Everyone must obey the *law*.', '모두가 법을 지켜야 한다.'],
        ['permission', 'n', '허가', 'You need *permission* to enter this room.', '이 방에 들어가려면 허가가 필요하다.'],
        ['violate', 'v', '위반하다', 'Drivers who *violate* the rule will be fined.', '규칙을 위반하는 운전자는 벌금을 물게 된다.'],
        ['punish', 'v', '처벌하다', 'The school will *punish* students who cheat.', '학교는 부정행위를 한 학생을 처벌할 것이다.'],
        ['legal', 'adj', '합법적인', 'Is it *legal* to park here?', '여기 주차하는 것이 합법인가요?'],
        ['illegal', 'adj', '불법적인', 'It is *illegal* to drive without a license.', '면허 없이 운전하는 것은 불법이다.'],
        ['regulation', 'n', '규정', 'The factory follows a strict safety *regulation*.', '그 공장은 엄격한 안전 규정을 따른다.'],
        ['violation', 'n', '위반', 'This is a clear *violation* of the rules.', '이것은 명백한 규칙 위반이다.'],
      ] },
      { name: '예술과 창작', words: [
        ['creative', 'adj', '창의적인', 'She has a very *creative* mind.', '그녀는 매우 창의적인 사고를 가지고 있다.'],
        ['inspire', 'v', '영감을 주다', 'Nature can *inspire* great artists.', '자연은 위대한 예술가들에게 영감을 줄 수 있다.'],
        ['masterpiece', 'n', '걸작', 'This novel is considered a *masterpiece*.', '이 소설은 걸작으로 여겨진다.'],
        ['sculpture', 'n', '조각품', 'The park has a famous bronze *sculpture*.', '그 공원에는 유명한 청동 조각품이 있다.'],
        ['exhibit', 'v', '전시하다', 'The museum will *exhibit* new paintings.', '그 박물관은 새 그림들을 전시할 것이다.'],
        ['melody', 'n', '선율, 멜로디', "I can't forget that beautiful *melody*.", '나는 그 아름다운 선율을 잊을 수 없다.'],
        ['imaginative', 'adj', '상상력이 풍부한', 'The children wrote an *imaginative* story.', '아이들은 상상력이 풍부한 이야기를 썼다.'],
        ['performance', 'n', '공연', 'The dance *performance* received great applause.', '그 무용 공연은 큰 박수를 받았다.'],
      ] },
      { name: '여행과 교통', words: [
        ['journey', 'n', '여행, 여정', 'Our *journey* across the country took five days.', '우리의 전국 여행은 5일이 걸렸다.'],
        ['destination', 'n', '목적지', 'The ship finally reached its *destination*.', '배는 마침내 목적지에 도착했다.'],
        ['luggage', 'n', '짐, 수하물', 'Please keep an eye on my *luggage*.', '제 짐 좀 봐 주세요.'],
        ['depart', 'v', '출발하다', 'The train will *depart* at nine sharp.', '기차는 정각 9시에 출발할 것이다.'],
        ['arrival', 'n', '도착', 'We waited at the gate for her *arrival*.', '우리는 그녀의 도착을 게이트에서 기다렸다.'],
        ['passenger', 'n', '승객', 'Every *passenger* must wear a seatbelt.', '모든 승객은 안전벨트를 매야 한다.'],
        ['route', 'n', '경로, 노선', 'This *route* avoids the heavy traffic.', '이 경로는 심한 교통체증을 피한다.'],
        ['delay', 'n', '지연', 'The flight suffered a two-hour *delay*.', '그 항공편은 두 시간 지연되었다.'],
      ] },
      { name: '스포츠와 취미', words: [
        ['athlete', 'n', '운동선수', 'The *athlete* trained for six hours a day.', '그 운동선수는 하루에 여섯 시간씩 훈련했다.'],
        ['compete', 'v', '경쟁하다, 겨루다', 'Two teams will *compete* in the final.', '두 팀이 결승전에서 겨룰 것이다.'],
        ['championship', 'n', '선수권 대회', 'She won the national *championship* last year.', '그녀는 작년에 전국 선수권 대회에서 우승했다.'],
        ['hobby', 'n', '취미', 'Painting is my favorite *hobby*.', '그림 그리기는 내가 가장 좋아하는 취미이다.'],
        ['referee', 'n', '심판', 'The *referee* stopped the game for a review.', '심판은 검토를 위해 경기를 멈췄다.'],
        ['opponent', 'n', '상대, 상대편', 'He shook hands with his *opponent*.', '그는 상대와 악수했다.'],
        ['victory', 'n', '승리', 'The team celebrated their *victory* all night.', '그 팀은 밤새 승리를 자축했다.'],
        ['defeat', 'v', '패배시키다, 물리치다', 'They managed to *defeat* the champion team.', '그들은 챔피언 팀을 물리치는 데 성공했다.'],
      ] },
      { name: '직업과 진로', words: [
        ['career', 'n', '경력', 'She started her *career* as a teacher.', '그녀는 교사로 경력을 시작했다.'],
        ['profession', 'n', '직업, 전문직', 'Medicine is a respected *profession*.', '의학은 존경받는 직업이다.'],
        ['qualify', 'v', '자격을 얻다', 'You must pass the exam to *qualify*.', '자격을 얻으려면 시험을 통과해야 한다.'],
        ['apply', 'v', '지원하다, 적용하다', 'I plan to *apply* for the internship.', '나는 그 인턴십에 지원할 계획이다.'],
        ['resume', 'n', '이력서', 'Send your *resume* before Friday.', '금요일 전에 이력서를 보내라.'],
        ['interview', 'n', '면접', 'He was nervous before the job *interview*.', '그는 취업 면접 전에 긴장했다.'],
        ['promotion', 'n', '승진', 'She received a *promotion* last month.', '그녀는 지난달 승진했다.'],
        ['retire', 'v', '은퇴하다', 'My grandfather plans to *retire* next year.', '할아버지는 내년에 은퇴하실 계획이다.'],
      ] },
      { name: '미디어와 소통', words: [
        ['media', 'n', '매체, 언론', 'Social *media* has changed how we communicate.', '소셜 미디어는 우리가 소통하는 방식을 바꾸었다.'],
        ['broadcast', 'v', '방송하다', 'The game will *broadcast* live tonight.', '그 경기는 오늘 밤 생방송될 것이다.'],
        ['journalist', 'n', '기자', 'A *journalist* interviewed the mayor.', '한 기자가 시장을 인터뷰했다.'],
        ['advertisement', 'n', '광고', 'This *advertisement* appears on every website.', '이 광고는 모든 웹사이트에 나타난다.'],
        ['audience', 'n', '청중, 관객', 'The *audience* applauded loudly.', '관객들은 크게 박수를 쳤다.'],
        ['headline', 'n', '표제, 헤드라인', "The *headline* caught everyone's attention.", '그 헤드라인은 모두의 관심을 끌었다.'],
        ['rumor', 'n', '소문', "Don't believe every *rumor* you hear.", '들리는 모든 소문을 믿지 마라.'],
        ['publish', 'v', '출판하다, 게시하다', 'The magazine will *publish* the article next week.', '그 잡지는 다음 주에 그 기사를 게재할 것이다.'],
      ] },
      { name: '수와 측정', words: [
        ['quantity', 'n', '양, 수량', 'Buy a large *quantity* of rice.', '쌀을 많은 양 사라.'],
        ['measure', 'v', '측정하다', 'Use this tool to *measure* the length.', '이 도구로 길이를 측정해라.'],
        ['average', 'adj', '평균의', 'The *average* score was seventy.', '평균 점수는 70점이었다.'],
        ['estimate', 'v', '추정하다', 'Experts *estimate* the cost at one million won.', '전문가들은 비용을 백만 원으로 추정한다.'],
        ['proportion', 'n', '비율', 'A large *proportion* of students passed.', '많은 비율의 학생들이 합격했다.'],
        ['calculate', 'v', '계산하다', 'Please *calculate* the total price.', '총 가격을 계산해 주세요.'],
        ['approximate', 'adj', '대략적인', 'Give me an *approximate* time of arrival.', '대략적인 도착 시간을 알려줘.'],
        ['double', 'v', '두 배로 되다, 늘리다', 'Sales will *double* by next year.', '매출은 내년까지 두 배가 될 것이다.'],
      ] },
      { name: '교육', words: [
        ['curriculum', 'n', '교육과정', 'The school updated its *curriculum* this year.', '그 학교는 올해 교육과정을 개편했다.'],
        ['academic', 'adj', '학업의, 학문의', 'Her *academic* performance improved a lot.', '그녀의 학업 성취도가 많이 향상되었다.'],
        ['tuition', 'n', '수업료, 등록금', 'College *tuition* keeps rising every year.', '대학 등록금은 매년 오르고 있다.'],
        ['scholarship', 'n', '장학금', 'He received a full *scholarship* to study abroad.', '그는 해외 유학을 위한 전액 장학금을 받았다.'],
        ['literacy', 'n', '문해력, 읽고 쓰는 능력', "Reading programs improve children's *literacy*.", '독서 프로그램은 아이들의 문해력을 향상시킨다.'],
        ['discipline', 'n', '훈육, 규율', 'Good *discipline* helps students focus.', '좋은 규율은 학생들이 집중하도록 돕는다.'],
        ['graduate', 'v', '졸업하다', 'She will *graduate* from high school next spring.', '그녀는 내년 봄에 고등학교를 졸업할 것이다.'],
        ['enroll', 'v', '등록하다', 'I plan to *enroll* in a coding class.', '나는 코딩 수업에 등록할 계획이다.'],
      ] },
      { name: '지리와 지형', words: [
        ['continent', 'n', '대륙', 'Africa is the second largest *continent*.', '아프리카는 두 번째로 큰 대륙이다.'],
        ['peninsula', 'n', '반도', 'Korea is located on a *peninsula*.', '한국은 반도에 위치해 있다.'],
        ['desert', 'n', '사막', 'Few plants survive in the *desert*.', '사막에서는 살아남는 식물이 거의 없다.'],
        ['plain', 'n', '평야, 평원', 'Farmers grow wheat on the wide *plain*.', '농부들은 넓은 평야에서 밀을 재배한다.'],
        ['coast', 'n', '해안', 'They spent the summer on the *coast*.', '그들은 여름을 해안에서 보냈다.'],
        ['altitude', 'n', '고도', 'The plane is flying at a high *altitude*.', '비행기는 높은 고도로 날고 있다.'],
        ['terrain', 'n', '지형', 'The *terrain* here is rocky and steep.', '이곳의 지형은 바위투성이이고 가파르다.'],
        ['equator', 'n', '적도', 'It is always hot near the *equator*.', '적도 근처는 항상 덥다.'],
      ] },
      { name: '소비와 경제생활', words: [
        ['purchase', 'v', '구매하다', 'She decided to *purchase* a new laptop.', '그녀는 새 노트북을 구매하기로 결정했다.'],
        ['afford', 'v', '여유가 되다, 감당하다', "We can't *afford* a new car right now.", '우리는 지금 새 차를 살 여유가 없다.'],
        ['discount', 'n', '할인', 'I got a 20% *discount* on these shoes.', '나는 이 신발을 20% 할인받았다.'],
        ['refund', 'n', '환불', 'The store offered a full *refund*.', '그 가게는 전액 환불을 해 주었다.'],
        ['consumer', 'n', '소비자', 'The *consumer* has many choices today.', '오늘날 소비자는 선택지가 많다.'],
        ['expense', 'n', '비용, 지출', 'Rent is my biggest monthly *expense*.', '집세는 내 월간 지출 중 가장 크다.'],
        ['income', 'n', '소득, 수입', "Their *income* increased after the promotion.", '승진 후 그들의 소득이 증가했다.'],
        ['bargain', 'n', '싸게 사는 물건, 흥정', 'This jacket was a real *bargain*.', '이 재킷은 정말 싸게 산 물건이었다.'],
      ] },
      { name: '갈등과 화해', words: [
        ['conflict', 'n', '갈등', 'The *conflict* between the brothers lasted for weeks.', '그 형제 사이의 갈등은 몇 주 동안 지속되었다.'],
        ['apologize', 'v', '사과하다', 'He decided to *apologize* for his mistake.', '그는 자신의 실수에 대해 사과하기로 했다.'],
        ['forgive', 'v', '용서하다', 'It took time, but she learned to *forgive* him.', '시간이 걸렸지만 그녀는 그를 용서하는 법을 배웠다.'],
        ['compromise', 'n', '타협', 'They reached a *compromise* after a long talk.', '그들은 긴 대화 끝에 타협에 이르렀다.'],
        ['tension', 'n', '긴장(감)', 'There was *tension* in the room before the meeting.', '회의 전 방 안에는 긴장감이 감돌았다.'],
        ['resolve', 'v', '해결하다', 'We need to *resolve* this issue quickly.', '우리는 이 문제를 빨리 해결해야 한다.'],
        ['misunderstand', 'v', '오해하다', 'I think you *misunderstand* my intention.', '네가 내 의도를 오해하고 있는 것 같아.'],
        ['reconcile', 'v', '화해시키다, 화해하다', 'The two friends finally decided to *reconcile*.', '두 친구는 마침내 화해하기로 했다.'],
      ] },
      { name: '자연 현상', words: [
        ['earthquake', 'n', '지진', 'The *earthquake* damaged many buildings.', '그 지진은 많은 건물을 훼손했다.'],
        ['volcano', 'n', '화산', 'The *volcano* erupted after years of silence.', '그 화산은 수년간의 잠잠함 끝에 분출했다.'],
        ['drought', 'n', '가뭄', 'The *drought* destroyed most of the crops.', '가뭄은 대부분의 농작물을 파괴했다.'],
        ['thunder', 'n', '천둥', 'Loud *thunder* woke the baby up.', '큰 천둥소리가 아기를 깨웠다.'],
        ['lightning', 'n', '번개', '*Lightning* struck the old tree.', '번개가 그 오래된 나무를 쳤다.'],
        ['tide', 'n', '조수, 파도', 'The *tide* comes in twice a day.', '조수는 하루에 두 번 밀려온다.'],
        ['erosion', 'n', '침식', 'Wind causes *erosion* on the cliffs.', '바람은 절벽에 침식을 일으킨다.'],
        ['humidity', 'n', '습도', 'The *humidity* makes summer feel hotter.', '습도는 여름을 더 덥게 느껴지게 한다.'],
      ] },
      { name: '농업과 식량', words: [
        ['agriculture', 'n', '농업', '*Agriculture* is the main industry in this region.', '농업은 이 지역의 주요 산업이다.'],
        ['harvest', 'v', '수확하다', 'Farmers *harvest* rice in autumn.', '농부들은 가을에 쌀을 수확한다.'],
        ['crop', 'n', '농작물', "Corn is the region's main *crop*.", '옥수수는 그 지역의 주요 농작물이다.'],
        ['livestock', 'n', '가축', 'The farm raises *livestock* for milk and meat.', '그 농장은 우유와 고기를 위해 가축을 기른다.'],
        ['fertile', 'adj', '비옥한', 'The soil here is very *fertile*.', '이곳의 토양은 매우 비옥하다.'],
        ['irrigation', 'n', '관개', '*Irrigation* helps crops grow in dry areas.', '관개는 건조한 지역에서 작물이 자라도록 돕는다.'],
        ['famine', 'n', '기근', 'The *famine* forced many people to leave.', '기근은 많은 사람들을 떠나게 만들었다.'],
        ['shortage', 'n', '부족', 'There was a food *shortage* after the storm.', '폭풍 이후 식량 부족이 있었다.'],
      ] },
      { name: '범죄와 안전', words: [
        ['crime', 'n', '범죄', 'The *crime* rate dropped this year.', '범죄율이 올해 떨어졌다.'],
        ['theft', 'n', '절도', 'The store reported a *theft* last night.', '그 가게는 어젯밤 절도를 신고했다.'],
        ['suspect', 'n', '용의자', 'Police arrested the main *suspect*.', '경찰은 주요 용의자를 체포했다.'],
        ['investigate', 'v', '수사하다, 조사하다', 'Detectives will *investigate* the case.', '형사들이 그 사건을 수사할 것이다.'],
        ['victim', 'n', '피해자', 'The *victim* was taken to the hospital.', '피해자는 병원으로 옮겨졌다.'],
        ['alarm', 'n', '경보(기)', 'The fire *alarm* went off suddenly.', '화재 경보기가 갑자기 울렸다.'],
        ['emergency', 'n', '비상사태, 응급상황', 'Call this number in case of an *emergency*.', '비상 상황 시 이 번호로 전화하세요.'],
        ['prevent', 'v', '예방하다, 막다', 'Locks *prevent* theft.', '자물쇠는 절도를 막는다.'],
      ] },
      { name: '건축과 주거', words: [
        ['architecture', 'n', '건축(학)', 'She studies *architecture* at university.', '그녀는 대학에서 건축학을 공부한다.'],
        ['construct', 'v', '건설하다, 짓다', 'They plan to *construct* a new bridge.', '그들은 새 다리를 건설할 계획이다.'],
        ['structure', 'n', '구조(물)', 'The old *structure* was torn down.', '그 오래된 구조물은 철거되었다.'],
        ['apartment', 'n', '아파트', 'They moved into a new *apartment*.', '그들은 새 아파트로 이사했다.'],
        ['furniture', 'n', '가구', 'We bought new *furniture* for the living room.', '우리는 거실에 놓을 새 가구를 샀다.'],
        ['renovate', 'v', '개조하다, 보수하다', 'They decided to *renovate* the old house.', '그들은 오래된 집을 개조하기로 했다.'],
        ['foundation', 'n', '기초, 토대', 'A strong *foundation* supports the building.', '튼튼한 기초가 건물을 지탱한다.'],
        ['landlord', 'n', '집주인', 'The *landlord* raised the rent this year.', '집주인은 올해 집세를 올렸다.'],
      ] },
      { name: '컴퓨터와 인터넷', words: [
        ['software', 'n', '소프트웨어', 'The company develops *software* for phones.', '그 회사는 휴대폰용 소프트웨어를 개발한다.'],
        ['upload', 'v', '업로드하다', 'I will *upload* the photos tonight.', '나는 오늘 밤 사진들을 업로드할 것이다.'],
        ['password', 'n', '비밀번호', 'Never share your *password* with strangers.', '낯선 사람에게 절대 비밀번호를 알려주지 마라.'],
        ['network', 'n', '네트워크, 망', 'The office has a fast *network*.', '사무실에는 빠른 네트워크가 있다.'],
        ['virus', 'n', '바이러스', 'A *virus* infected his computer.', '바이러스가 그의 컴퓨터를 감염시켰다.'],
        ['browse', 'v', '검색하다, 둘러보다', 'I like to *browse* the web at night.', '나는 밤에 인터넷을 둘러보는 것을 좋아한다.'],
        ['install', 'v', '설치하다', 'Please *install* the new update.', '새 업데이트를 설치해 주세요.'],
        ['database', 'n', '데이터베이스', 'The company stores data in a large *database*.', '그 회사는 큰 데이터베이스에 자료를 저장한다.'],
      ] },
      { name: '신체와 감각', words: [
        ['skeleton', 'n', '골격, 해골', 'The museum displays a dinosaur *skeleton*.', '그 박물관은 공룡 골격을 전시한다.'],
        ['muscle', 'n', '근육', 'Lifting weights builds *muscle*.', '역기를 드는 것은 근육을 키운다.'],
        ['breathe', 'v', '숨 쉬다, 호흡하다', 'Take a moment to *breathe* deeply.', '잠시 깊게 숨을 쉬어라.'],
        ['sense', 'n', '감각', 'Touch is one important *sense*.', '촉각은 중요한 감각 중 하나이다.'],
        ['vision', 'n', '시력, 시야', 'Her *vision* improved after the surgery.', '수술 후 그녀의 시력이 좋아졌다.'],
        ['sensitive', 'adj', '민감한', 'His skin is *sensitive* to sunlight.', '그의 피부는 햇빛에 민감하다.'],
        ['numb', 'adj', '감각이 없는, 마비된', 'My fingers felt *numb* in the cold.', '추위 속에서 내 손가락이 감각이 없게 느껴졌다.'],
        ['reflex', 'n', '반사 작용', 'The doctor tested his knee *reflex*.', '의사는 그의 무릎 반사 작용을 검사했다.'],
      ] },
      { name: '패션과 외모', words: [
        ['fashion', 'n', '패션, 유행', 'She always follows the latest *fashion*.', '그녀는 항상 최신 유행을 따른다.'],
        ['appearance', 'n', '외모, 겉모습', "Don't judge people by their *appearance*.", '외모로 사람을 판단하지 마라.'],
        ['fabric', 'n', '천, 직물', 'This dress is made of soft *fabric*.', '이 드레스는 부드러운 천으로 만들어졌다.'],
        ['trend', 'n', '유행, 경향', 'Short hair is a popular *trend* this year.', '짧은 머리는 올해 인기 있는 유행이다.'],
        ['elegant', 'adj', '우아한', 'She wore an *elegant* dress to the party.', '그녀는 파티에 우아한 드레스를 입고 왔다.'],
        ['casual', 'adj', '평상복의, 격식 없는', 'I prefer *casual* clothes on weekends.', '나는 주말에 평상복을 선호한다.'],
        ['accessory', 'n', '액세서리, 장신구', 'A necklace is a nice *accessory*.', '목걸이는 멋진 액세서리이다.'],
        ['trendy', 'adj', '최신 유행의', 'That cafe looks very *trendy*.', '그 카페는 아주 최신 유행인 것 같다.'],
      ] },
      { name: '영화와 공연예술', words: [
        ['director', 'n', '감독', 'The *director* won an award for the film.', '그 감독은 그 영화로 상을 받았다.'],
        ['actor', 'n', '배우', 'He is a famous *actor* in Korea.', '그는 한국에서 유명한 배우이다.'],
        ['scene', 'n', '장면', 'That *scene* made the whole audience cry.', '그 장면은 모든 관객을 울렸다.'],
        ['script', 'n', '대본, 각본', 'She wrote the *script* for the play.', '그녀는 그 연극의 대본을 썼다.'],
        ['audition', 'n', '오디션', 'He passed the *audition* for the musical.', '그는 그 뮤지컬 오디션에 합격했다.'],
        ['rehearse', 'v', '연습하다, 리허설하다', 'The cast will *rehearse* every evening.', '출연진은 매일 저녁 연습할 것이다.'],
        ['costume', 'n', '의상', 'Each actor wore a colorful *costume*.', '각 배우는 화려한 의상을 입었다.'],
        ['applause', 'n', '박수(갈채)', 'The show ended with loud *applause*.', '공연은 큰 박수로 끝났다.'],
      ] },
      { name: '교통수단과 운전', words: [
        ['vehicle', 'n', '차량, 탈것', 'This *vehicle* can carry six people.', '이 차량은 여섯 명을 태울 수 있다.'],
        ['license', 'n', '면허(증)', "You need a driver's *license* to drive.", '운전하려면 운전면허가 필요하다.'],
        ['traffic', 'n', '교통(량)', '*Traffic* was heavy this morning.', '오늘 아침 교통이 혼잡했다.'],
        ['signal', 'n', '신호', 'Stop when the *signal* turns red.', '신호가 빨간불로 바뀌면 멈춰라.'],
        ['brake', 'n', '브레이크, 제동장치', 'He hit the *brake* suddenly.', '그는 갑자기 브레이크를 밟았다.'],
        ['fuel', 'n', '연료', 'The car ran out of *fuel*.', '그 차는 연료가 떨어졌다.'],
        ['collide', 'v', '충돌하다', 'The driver tried not to *collide* with the truck.', '그 운전자는 트럭과 충돌하지 않으려 했다.'],
        ['pedestrian', 'n', '보행자', 'Drivers must yield to a *pedestrian*.', '운전자는 보행자에게 양보해야 한다.'],
      ] },
      { name: '동물과 곤충', words: [
        ['mammal', 'n', '포유류', 'A whale is a *mammal*, not a fish.', '고래는 어류가 아니라 포유류이다.'],
        ['insect', 'n', '곤충', 'A bee is a helpful *insect*.', '벌은 유익한 곤충이다.'],
        ['predator', 'n', '포식자', 'A lion is a top *predator*.', '사자는 최상위 포식자이다.'],
        ['prey', 'n', '먹이', 'The eagle caught its *prey*.', '독수리는 먹이를 잡았다.'],
        ['species', 'n', '종(생물 분류)', 'This *species* is found only in Korea.', '이 종은 한국에서만 발견된다.'],
        ['habitat', 'n', '서식지', 'Deforestation destroys animal *habitat*.', '삼림 벌채는 동물 서식지를 파괴한다.'],
        ['breed', 'v', '번식하다, 사육하다', 'Rabbits *breed* very quickly.', '토끼는 매우 빠르게 번식한다.'],
        ['endangered', 'adj', '멸종 위기에 처한', 'The panda is an *endangered* animal.', '판다는 멸종 위기에 처한 동물이다.'],
      ] },
      { name: '시간과 일정관리', words: [
        ['appointment', 'n', '약속, 예약', 'I have a dentist *appointment* at three.', '나는 3시에 치과 예약이 있다.'],
        ['punctual', 'adj', '시간을 잘 지키는', 'Please be *punctual* for the meeting.', '회의에 시간을 잘 지켜 주세요.'],
        ['reschedule', 'v', '일정을 변경하다', 'We need to *reschedule* the appointment.', '우리는 약속 일정을 변경해야 한다.'],
        ['urgent', 'adj', '긴급한', 'This is an *urgent* matter.', '이것은 긴급한 사안이다.'],
        ['routine', 'n', '일상, 루틴', 'Exercise is part of my daily *routine*.', '운동은 내 일상의 일부이다.'],
        ['productive', 'adj', '생산적인', 'We had a *productive* meeting today.', '우리는 오늘 생산적인 회의를 했다.'],
        ['overdue', 'adj', '기한이 지난, 연체된', 'This library book is *overdue*.', '이 도서관 책은 반납 기한이 지났다.'],
        ['procrastinate', 'v', '미루다, 꾸물거리다', 'He tends to *procrastinate* before exams.', '그는 시험 전에 꾸물거리는 경향이 있다.'],
      ] },
    ],
  },
  {
    id: 4, name: '숲', icon: '🌲', desc: '수능·토익 필수',
    stages: [
      { name: '비즈니스', words: [
        ['schedule', 'n', '일정', 'Check the meeting *schedule*.', '회의 일정을 확인하세요.'],
        ['invoice', 'n', '청구서', 'Please send the *invoice* by Friday.', '금요일까지 청구서를 보내 주세요.'],
        ['negotiate', 'v', '협상하다', 'We will *negotiate* the price tomorrow.', '우리는 내일 가격을 협상할 것이다.'],
        ['deadline', 'n', '마감 기한', 'The *deadline* is next Monday.', '마감 기한은 다음 주 월요일이다.'],
        ['contract', 'n', '계약서', 'Both sides signed the *contract*.', '양측이 계약서에 서명했다.'],
        ['revenue', 'n', '수익, 매출', 'Company *revenue* rose by ten percent.', '회사 매출이 10퍼센트 올랐다.'],
        ['colleague', 'n', '동료', 'My *colleague* will cover for me.', '내 동료가 나 대신 맡아 줄 것이다.'],
        ['supervisor', 'n', '상사, 감독관', 'Ask your *supervisor* for approval.', '상사에게 승인을 요청하세요.'],
      ] },
      { name: '논리와 주장', words: [
        ['argue', 'v', '주장하다, 논쟁하다', 'Some experts *argue* that sleep is essential.', '일부 전문가들은 수면이 필수적이라고 주장한다.'],
        ['emphasize', 'v', '강조하다', 'Teachers often *emphasize* the importance of reading.', '교사들은 독서의 중요성을 자주 강조한다.'],
        ['contradict', 'v', '모순되다, 반박하다', 'His actions *contradict* his words.', '그의 행동은 그의 말과 모순된다.'],
        ['inevitable', 'adj', '불가피한', 'Change is *inevitable*.', '변화는 불가피하다.'],
        ['reluctant', 'adj', '꺼리는', 'He was *reluctant* to admit his mistake.', '그는 자신의 실수를 인정하기를 꺼렸다.'],
        ['controversial', 'adj', '논란이 많은', 'It is a *controversial* topic.', '그것은 논란이 많은 주제이다.'],
        ['justify', 'v', '정당화하다', 'Nothing can *justify* violence.', '어떤 것도 폭력을 정당화할 수 없다.'],
        ['implication', 'n', '함의, 영향', 'The *implication* of the study is serious.', '그 연구가 시사하는 바는 심각하다.'],
      ] },
      { name: '경제와 사회', words: [
        ['inflation', 'n', '물가 상승', 'High *inflation* hurts families.', '높은 물가 상승은 가계에 타격을 준다.'],
        ['budget', 'n', '예산', 'We need to stay within our *budget*.', '우리는 예산 안에서 지내야 한다.'],
        ['tax', 'n', '세금', 'You must pay income *tax*.', '소득세를 내야 한다.'],
        ['profit', 'n', '이익', 'The shop made a small *profit*.', '그 가게는 작은 이익을 냈다.'],
        ['unemployment', 'n', '실업', 'Youth *unemployment* is a serious problem.', '청년 실업은 심각한 문제이다.'],
        ['immigrant', 'n', '이민자', 'Each *immigrant* brings new ideas.', '이민자들은 저마다 새로운 아이디어를 가져온다.'],
        ['inequality', 'n', '불평등', 'Education can reduce *inequality*.', '교육은 불평등을 줄일 수 있다.'],
        ['subsidy', 'n', '보조금', 'Farmers receive a government *subsidy*.', '농부들은 정부 보조금을 받는다.'],
      ] },
      { name: '고난도 동사', words: [
        ['undermine', 'v', '약화시키다', 'Rumors can *undermine* trust.', '소문은 신뢰를 약화시킬 수 있다.'],
        ['enhance', 'v', '강화하다, 높이다', 'Music can *enhance* your memory.', '음악은 기억력을 높여 줄 수 있다.'],
        ['overcome', 'v', '극복하다', 'You can *overcome* any difficulty.', '너는 어떤 어려움도 극복할 수 있다.'],
        ['adapt', 'v', '적응하다', 'Animals *adapt* to their surroundings.', '동물들은 주변 환경에 적응한다.'],
        ['diminish', 'v', '줄어들다, 약해지다', 'Her fear began to *diminish*.', '그녀의 두려움이 줄어들기 시작했다.'],
        ['demonstrate', 'v', '입증하다, 보여주다', 'The experiment will *demonstrate* the idea.', '그 실험이 그 생각을 입증할 것이다.'],
        ['obtain', 'v', '얻다, 획득하다', 'You must *obtain* a permit first.', '먼저 허가증을 얻어야 한다.'],
        ['postpone', 'v', '연기하다', 'They had to *postpone* the game.', '그들은 경기를 연기해야 했다.'],
      ] },
      { name: '심리와 인지', words: [
        ['perceive', 'v', '인지하다, 지각하다', 'We *perceive* colors differently in dim light.', '우리는 어두운 빛 속에서 색깔을 다르게 지각한다.'],
        ['cognitive', 'adj', '인지의', 'The test measures *cognitive* ability.', '그 검사는 인지 능력을 측정한다.'],
        ['motivate', 'v', '동기를 부여하다', 'Good teachers *motivate* their students.', '좋은 교사는 학생들에게 동기를 부여한다.'],
        ['instinct', 'n', '본능', 'Animals rely on *instinct* to survive.', '동물들은 생존을 위해 본능에 의존한다.'],
        ['subconscious', 'adj', '잠재의식의', 'Our *subconscious* mind affects our choices.', '우리의 잠재의식은 선택에 영향을 미친다.'],
        ['perception', 'n', '인식, 지각', 'Public *perception* of the issue has changed.', '그 사안에 대한 대중의 인식이 변했다.'],
        ['rational', 'adj', '이성적인, 합리적인', 'Try to make a *rational* decision.', '이성적인 결정을 내리려고 노력해라.'],
        ['intuition', 'n', '직관', 'She trusted her *intuition* and left early.', '그녀는 직관을 믿고 일찍 떠났다.'],
      ] },
      { name: '환경과 지속가능성', words: [
        ['sustainable', 'adj', '지속 가능한', 'We need *sustainable* energy sources.', '우리는 지속 가능한 에너지원이 필요하다.'],
        ['emission', 'n', '배출(물)', 'The new law will cut carbon *emission*.', '새 법은 탄소 배출을 줄일 것이다.'],
        ['renewable', 'adj', '재생 가능한', 'Solar power is a *renewable* resource.', '태양광은 재생 가능한 자원이다.'],
        ['conserve', 'v', '보존하다, 아끼다', 'We should *conserve* water during the drought.', '가뭄 동안 우리는 물을 아껴야 한다.'],
        ['ecosystem', 'n', '생태계', 'Pollution can destroy an entire *ecosystem*.', '오염은 생태계 전체를 파괴할 수 있다.'],
        ['extinct', 'adj', '멸종된', 'The dodo bird became *extinct* long ago.', '도도새는 오래전에 멸종되었다.'],
        ['deforestation', 'n', '삼림 벌채', '*Deforestation* is a major cause of climate change.', '삼림 벌채는 기후 변화의 주요 원인이다.'],
        ['pollutant', 'n', '오염 물질', 'Factories release a harmful *pollutant* into the river.', '공장들은 강에 해로운 오염 물질을 배출한다.'],
      ] },
      { name: '국제 관계', words: [
        ['diplomat', 'n', '외교관', 'The *diplomat* met with foreign leaders.', '그 외교관은 외국 지도자들을 만났다.'],
        ['treaty', 'n', '조약', 'The two countries signed a peace *treaty*.', '두 나라는 평화 조약에 서명했다.'],
        ['alliance', 'n', '동맹', 'The nations formed a military *alliance*.', '그 국가들은 군사 동맹을 맺었다.'],
        ['sovereignty', 'n', '주권', 'The country fought to protect its *sovereignty*.', '그 나라는 주권을 지키기 위해 싸웠다.'],
        ['refugee', 'n', '난민', 'The camp provides shelter for every *refugee*.', '그 수용소는 모든 난민에게 쉼터를 제공한다.'],
        ['embassy', 'n', '대사관', 'She works at the Korean *embassy* in Paris.', '그녀는 파리에 있는 한국 대사관에서 일한다.'],
        ['diplomatic', 'adj', '외교의, 외교적인', 'They tried to find a *diplomatic* solution.', '그들은 외교적인 해결책을 찾으려 했다.'],
        ['negotiation', 'n', '협상', 'The *negotiation* lasted for three days.', '그 협상은 사흘 동안 계속되었다.'],
      ] },
      { name: '고급 형용사', words: [
        ['subtle', 'adj', '미묘한', 'There is a *subtle* difference between the two colors.', '그 두 색깔 사이에는 미묘한 차이가 있다.'],
        ['ambiguous', 'adj', '모호한', 'His answer was *ambiguous* and confusing.', '그의 대답은 모호하고 혼란스러웠다.'],
        ['profound', 'adj', '깊은, 심오한', 'The book had a *profound* effect on me.', '그 책은 나에게 깊은 영향을 미쳤다.'],
        ['versatile', 'adj', '다재다능한, 다용도의', 'She is a *versatile* actress.', '그녀는 다재다능한 배우이다.'],
        ['meticulous', 'adj', '꼼꼼한, 세심한', 'He is *meticulous* about every detail.', '그는 모든 세부 사항에 꼼꼼하다.'],
        ['tedious', 'adj', '지루한, 따분한', 'Filling out forms can be *tedious*.', '양식을 작성하는 것은 지루할 수 있다.'],
        ['plausible', 'adj', '그럴듯한, 타당한', 'Her explanation sounded *plausible*.', '그녀의 설명은 그럴듯하게 들렸다.'],
        ['redundant', 'adj', '불필요한, 중복된', 'Some of the words in the essay are *redundant*.', '그 에세이의 일부 단어는 불필요하다.'],
      ] },
      { name: '학술 명사', words: [
        ['hypothesis', 'n', '가설', 'The scientist tested her *hypothesis*.', '그 과학자는 자신의 가설을 검증했다.'],
        ['methodology', 'n', '방법론', 'The report explains the research *methodology*.', '그 보고서는 연구 방법론을 설명한다.'],
        ['variable', 'n', '변수', 'Temperature is an important *variable* in the experiment.', '온도는 그 실험에서 중요한 변수이다.'],
        ['correlation', 'n', '상관관계', 'There is a strong *correlation* between sleep and health.', '수면과 건강 사이에는 강한 상관관계가 있다.'],
        ['criteria', 'n', '기준(들)', 'The judges use strict *criteria* to score the contest.', '심사위원들은 엄격한 기준으로 대회 점수를 매긴다.'],
        ['phenomenon', 'n', '현상', 'Global warming is a well-known *phenomenon*.', '지구 온난화는 잘 알려진 현상이다.'],
        ['statistics', 'n', '통계', 'The *statistics* show a clear trend.', '그 통계는 분명한 추세를 보여준다.'],
        ['theoretical', 'adj', '이론적인', 'This is a *theoretical* model, not a real one.', '이것은 실제가 아니라 이론적인 모델이다.'],
      ] },
      { name: '철학과 윤리', words: [
        ['ethical', 'adj', '윤리적인', 'It is not *ethical* to lie to customers.', '고객에게 거짓말하는 것은 윤리적이지 않다.'],
        ['moral', 'adj', '도덕적인', 'She faced a difficult *moral* choice.', '그녀는 어려운 도덕적 선택에 직면했다.'],
        ['virtue', 'n', '미덕', 'Patience is considered a great *virtue*.', '인내는 큰 미덕으로 여겨진다.'],
        ['dilemma', 'n', '딜레마, 난제', 'He faced a moral *dilemma* at work.', '그는 직장에서 도덕적 딜레마에 직면했다.'],
        ['principle', 'n', '원칙', 'She never gives up her core *principle*.', '그녀는 자신의 핵심 원칙을 절대 포기하지 않는다.'],
        ['conscience', 'n', '양심', 'His *conscience* would not let him cheat.', '그의 양심은 그가 부정행위를 하도록 두지 않았다.'],
        ['justice', 'n', '정의', 'The court seeks *justice* for the victim.', '법원은 피해자를 위한 정의를 추구한다.'],
        ['integrity', 'n', '진실성, 정직성', 'A good leader acts with *integrity*.', '좋은 지도자는 진실성을 가지고 행동한다.'],
      ] },
      { name: '우주와 천문학', words: [
        ['universe', 'n', '우주', 'Scientists study how the *universe* began.', '과학자들은 우주가 어떻게 시작되었는지 연구한다.'],
        ['galaxy', 'n', '은하', 'Our *galaxy* contains billions of stars.', '우리 은하에는 수십억 개의 별이 있다.'],
        ['orbit', 'v', '궤도를 돌다', 'The moon continues to *orbit* the Earth.', '달은 계속 지구 궤도를 돈다.'],
        ['telescope', 'n', '망원경', 'He watched the stars through a *telescope*.', '그는 망원경으로 별을 관찰했다.'],
        ['gravity', 'n', '중력', '*Gravity* keeps us on the ground.', '중력은 우리를 땅에 붙잡아 둔다.'],
        ['astronaut', 'n', '우주비행사', 'The *astronaut* spent six months in space.', '그 우주비행사는 우주에서 6개월을 보냈다.'],
        ['asteroid', 'n', '소행성', 'An *asteroid* passed close to Earth.', '소행성 하나가 지구 가까이 지나갔다.'],
        ['satellite', 'n', '위성', 'The *satellite* sends weather data to Earth.', '그 위성은 지구로 기상 데이터를 보낸다.'],
      ] },
      { name: '노동과 산업', words: [
        ['labor', 'n', '노동', 'The factory relies on cheap *labor*.', '그 공장은 값싼 노동력에 의존한다.'],
        ['manufacture', 'v', '제조하다', 'The company plans to *manufacture* cars in a new factory.', '그 회사는 새 공장에서 자동차를 제조할 계획이다.'],
        ['industry', 'n', '산업', 'The tech *industry* grows every year.', '기술 산업은 매년 성장한다.'],
        ['output', 'n', '생산량', 'Factory *output* increased this quarter.', '공장 생산량이 이번 분기에 증가했다.'],
        ['efficient', 'adj', '효율적인', 'This machine is more *efficient* than the old one.', '이 기계는 예전 것보다 더 효율적이다.'],
        ['automation', 'n', '자동화', '*Automation* has changed many factory jobs.', '자동화는 많은 공장 일자리를 바꾸었다.'],
        ['workforce', 'n', '노동력, 근로자', 'The company has a skilled *workforce*.', '그 회사는 숙련된 노동력을 보유하고 있다.'],
        ['strike', 'n', '파업', 'Workers held a *strike* for better pay.', '근로자들은 더 나은 임금을 위해 파업을 벌였다.'],
      ] },
      { name: '심화 동사', words: [
        ['allocate', 'v', '할당하다, 분배하다', 'The budget will *allocate* more funds to education.', '예산은 교육에 더 많은 자금을 할당할 것이다.'],
        ['compensate', 'v', '보상하다', 'The company agreed to *compensate* the workers.', '회사는 근로자들에게 보상하기로 합의했다.'],
        ['derive', 'v', '유래하다, 끌어내다', 'The word seems to *derive* from Latin.', '그 단어는 라틴어에서 유래한 것으로 보인다.'],
        ['facilitate', 'v', '촉진하다, 용이하게 하다', 'New tools can *facilitate* learning.', '새로운 도구는 학습을 촉진할 수 있다.'],
        ['manipulate', 'v', '조작하다', 'He tried to *manipulate* the data.', '그는 데이터를 조작하려 했다.'],
        ['prioritize', 'v', '우선시하다', 'We need to *prioritize* safety first.', '우리는 안전을 가장 우선시해야 한다.'],
        ['reinforce', 'v', '강화하다', 'Practice will *reinforce* what you learned.', '연습은 네가 배운 것을 강화해 줄 것이다.'],
        ['withstand', 'v', '견디다, 버티다', 'The bridge must *withstand* strong winds.', '그 다리는 강풍을 견뎌야 한다.'],
      ] },
      { name: '군사와 안보', words: [
        ['military', 'adj', '군사의', 'The country increased its *military* budget.', '그 나라는 군사 예산을 늘렸다.'],
        ['defense', 'n', '방어, 국방', 'The missile system is for *defense* only.', '그 미사일 시스템은 방어용일 뿐이다.'],
        ['invade', 'v', '침략하다', 'Enemy forces threatened to *invade* the border.', '적군은 국경을 침략하겠다고 위협했다.'],
        ['weapon', 'n', '무기', 'They banned the use of that *weapon*.', '그들은 그 무기의 사용을 금지했다.'],
        ['troop', 'n', '병력, 부대', 'A *troop* of soldiers arrived at dawn.', '한 무리의 군인들이 새벽에 도착했다.'],
        ['surrender', 'v', '항복하다', 'The enemy had no choice but to *surrender*.', '적군은 항복할 수밖에 없었다.'],
        ['ceasefire', 'n', '휴전', 'Both sides agreed to a *ceasefire*.', '양측은 휴전에 합의했다.'],
        ['security', 'n', '보안, 안보', 'Airport *security* checks every bag.', '공항 보안은 모든 가방을 검사한다.'],
      ] },
      { name: '법률 용어', words: [
        ['testimony', 'n', '증언', "Her *testimony* convinced the jury.", '그녀의 증언은 배심원단을 설득했다.'],
        ['verdict', 'n', '평결, 판결', 'The jury reached a *verdict* after two days.', '배심원단은 이틀 만에 평결을 내렸다.'],
        ['litigation', 'n', '소송', 'The companies are involved in a long *litigation*.', '그 회사들은 긴 소송에 연루되어 있다.'],
        ['witness', 'n', '목격자, 증인', 'A *witness* described the accident in detail.', '한 목격자가 그 사고를 자세히 설명했다.'],
        ['prosecute', 'v', '기소하다', 'The government will *prosecute* those responsible.', '정부는 책임자들을 기소할 것이다.'],
        ['acquit', 'v', '무죄를 선고하다', 'The court decided to *acquit* the defendant.', '법원은 피고인에게 무죄를 선고하기로 했다.'],
        ['legislation', 'n', '법률, 입법', "New *legislation* will protect workers' rights.", '새 법률은 근로자의 권리를 보호할 것이다.'],
        ['jurisdiction', 'n', '관할권', "This case falls outside the court's *jurisdiction*.", '이 사건은 그 법원의 관할권 밖이다.'],
      ] },
      { name: '생명과학', words: [
        ['organism', 'n', '유기체, 생물', 'Every *organism* needs energy to survive.', '모든 유기체는 생존을 위해 에너지가 필요하다.'],
        ['genetic', 'adj', '유전의', 'The disease has a *genetic* cause.', '그 질병은 유전적 원인이 있다.'],
        ['evolve', 'v', '진화하다', 'Species *evolve* over millions of years.', '종은 수백만 년에 걸쳐 진화한다.'],
        ['molecule', 'n', '분자', 'Water is made of a simple *molecule*.', '물은 단순한 분자로 이루어져 있다.'],
        ['cell', 'n', '세포', 'A single *cell* can divide into two.', '하나의 세포는 둘로 분열할 수 있다.'],
        ['bacteria', 'n', '박테리아, 세균', '*Bacteria* can be helpful or harmful.', '박테리아는 유익할 수도 해로울 수도 있다.'],
        ['antibody', 'n', '항체', 'The body produces an *antibody* to fight the virus.', '몸은 바이러스와 싸우기 위해 항체를 생성한다.'],
        ['metabolism', 'n', '신진대사', 'Exercise can speed up your *metabolism*.', '운동은 신진대사를 촉진할 수 있다.'],
      ] },
      { name: '수사학과 설득', words: [
        ['persuade', 'v', '설득하다', 'She tried to *persuade* him to stay.', '그녀는 그가 머물도록 설득하려 했다.'],
        ['rhetoric', 'n', '수사(법), 화법', 'His speech was full of empty *rhetoric*.', '그의 연설은 공허한 수사로 가득했다.'],
        ['exaggerate', 'v', '과장하다', "Don't *exaggerate* the problem.", '문제를 과장하지 마라.'],
        ['imply', 'v', '암시하다', 'Her tone seemed to *imply* doubt.', '그녀의 말투는 의심을 암시하는 것 같았다.'],
        ['persuasive', 'adj', '설득력 있는', 'He gave a *persuasive* argument.', '그는 설득력 있는 주장을 펼쳤다.'],
        ['skeptical', 'adj', '회의적인', 'Many scientists remain *skeptical* of the claim.', '많은 과학자들은 그 주장에 여전히 회의적이다.'],
        ['coherent', 'adj', '일관성 있는, 논리정연한', 'Write a *coherent* essay with clear points.', '명확한 요점이 있는 일관성 있는 에세이를 써라.'],
        ['rebuttal', 'n', '반박', 'The lawyer offered a strong *rebuttal*.', '그 변호사는 강력한 반박을 제시했다.'],
      ] },
      { name: '시장과 소비자', words: [
        ['monopoly', 'n', '독점', 'The company held a *monopoly* on steel production.', '그 회사는 철강 생산을 독점했다.'],
        ['demand', 'n', '수요', '*Demand* for electric cars is rising fast.', '전기차에 대한 수요가 빠르게 증가하고 있다.'],
        ['supply', 'n', '공급', 'The *supply* of fresh water is limited.', '담수의 공급은 제한적이다.'],
        ['commodity', 'n', '상품, 원자재', 'Oil is a valuable global *commodity*.', '석유는 소중한 세계적 원자재이다.'],
        ['merger', 'n', '합병', 'The two banks announced a *merger*.', '두 은행은 합병을 발표했다.'],
        ['stock', 'n', '주식', 'He invested his savings in *stock*.', '그는 저축한 돈을 주식에 투자했다.'],
        ['bankrupt', 'adj', '파산한', 'The store went *bankrupt* last year.', '그 가게는 작년에 파산했다.'],
        ['investment', 'n', '투자', 'Education is the best *investment* for the future.', '교육은 미래를 위한 최고의 투자이다.'],
      ] },
      { name: '문학과 비평', words: [
        ['metaphor', 'n', '은유', 'The poem uses a powerful *metaphor*.', '그 시는 강력한 은유를 사용한다.'],
        ['narrative', 'n', '서사, 이야기', 'The film tells a touching *narrative*.', '그 영화는 감동적인 이야기를 들려준다.'],
        ['protagonist', 'n', '주인공', 'The *protagonist* faces many challenges.', '주인공은 많은 어려움에 직면한다.'],
        ['irony', 'n', '반어법, 아이러니', 'The ending is full of *irony*.', '그 결말은 아이러니로 가득하다.'],
        ['critique', 'n', '비평', 'The professor wrote a detailed *critique* of the novel.', '교수는 그 소설에 대한 상세한 비평을 썼다.'],
        ['symbolic', 'adj', '상징적인', 'The white bird is *symbolic* of peace.', '흰 새는 평화를 상징한다.'],
        ['genre', 'n', '장르', 'Mystery is her favorite *genre*.', '미스터리는 그녀가 가장 좋아하는 장르이다.'],
        ['theme', 'n', '주제', 'Loss is the main *theme* of the story.', '상실은 그 이야기의 주된 주제이다.'],
      ] },
      { name: '에너지와 자원', words: [
        ['resource', 'n', '자원', 'Water is a precious natural *resource*.', '물은 소중한 천연자원이다.'],
        ['fossil', 'adj', '화석의', '*Fossil* fuels cause pollution.', '화석 연료는 오염을 일으킨다.'],
        ['consumption', 'n', '소비, 소모', '*Consumption* rises in summer.', '여름에는 소비가 증가한다.'],
        ['depletion', 'n', '고갈', '*Depletion* of resources worries scientists.', '자원의 고갈은 과학자들을 걱정시킨다.'],
        ['petroleum', 'n', '석유', '*Petroleum* is refined into gasoline.', '석유는 정제되어 휘발유가 된다.'],
        ['nuclear', 'adj', '원자력의, 핵의', 'The country relies on *nuclear* power.', '그 나라는 원자력 발전에 의존한다.'],
        ['reserve', 'n', '비축량, 매장량', 'The nation has a large oil *reserve*.', '그 나라는 큰 석유 매장량을 보유하고 있다.'],
        ['scarce', 'adj', '부족한, 드문', 'Clean water is *scarce* in this area.', '이 지역은 깨끗한 물이 부족하다.'],
      ] },
      { name: '종교와 신념', words: [
        ['religion', 'n', '종교', '*Religion* plays a big role in her life.', '종교는 그녀의 삶에서 큰 역할을 한다.'],
        ['belief', 'n', '신념, 믿음', 'He holds a strong *belief* in equality.', '그는 평등에 대한 강한 신념을 가지고 있다.'],
        ['worship', 'v', '숭배하다, 예배하다', 'They gather every week to *worship*.', '그들은 매주 모여 예배한다.'],
        ['sacred', 'adj', '신성한', 'This mountain is *sacred* to the local people.', '이 산은 현지인들에게 신성하다.'],
        ['ceremony', 'n', '의식, 예식', 'The wedding *ceremony* lasted an hour.', '결혼식은 한 시간 동안 계속되었다.'],
        ['faith', 'n', '신앙, 믿음', 'She never lost her *faith*.', '그녀는 신앙을 잃지 않았다.'],
        ['spiritual', 'adj', '영적인', 'He went on a *spiritual* journey.', '그는 영적인 여정을 떠났다.'],
        ['doctrine', 'n', '교리', 'Each religion has its own *doctrine*.', '각 종교는 저마다의 교리가 있다.'],
      ] },
      { name: '복지와 사회정책', words: [
        ['welfare', 'n', '복지', 'The government increased *welfare* spending.', '정부는 복지 지출을 늘렸다.'],
        ['pension', 'n', '연금', 'She receives a monthly *pension*.', '그녀는 매달 연금을 받는다.'],
        ['disability', 'n', '장애', 'The building is accessible for people with a *disability*.', '그 건물은 장애가 있는 사람들도 이용할 수 있다.'],
        ['charity', 'n', '자선, 자선단체', 'He donates to *charity* every year.', '그는 매년 자선단체에 기부한다.'],
        ['poverty', 'n', '빈곤', '*Poverty* remains a serious issue worldwide.', '빈곤은 전 세계적으로 여전히 심각한 문제이다.'],
        ['homeless', 'adj', '노숙자의, 집 없는', 'The shelter helps *homeless* people.', '그 보호소는 노숙자들을 돕는다.'],
        ['aid', 'n', '원조, 지원', 'The country received foreign *aid* after the flood.', '그 나라는 홍수 이후 해외 원조를 받았다.'],
        ['vulnerable', 'adj', '취약한', 'Elderly people are *vulnerable* to the cold.', '노인들은 추위에 취약하다.'],
      ] },
      { name: '논리적 오류와 편향', words: [
        ['bias', 'n', '편향', 'The study may contain *bias*.', '그 연구는 편향을 포함할 수도 있다.'],
        ['fallacy', 'n', '오류', 'His argument is based on a logical *fallacy*.', '그의 주장은 논리적 오류에 근거한다.'],
        ['stereotype', 'n', '고정관념', 'She tried to break the *stereotype*.', '그녀는 고정관념을 깨려 했다.'],
        ['prejudice', 'n', '편견', '*Prejudice* often comes from ignorance.', '편견은 흔히 무지에서 비롯된다.'],
        ['objective', 'adj', '객관적인', 'Try to stay *objective* when judging.', '판단할 때는 객관적인 태도를 유지하려 해라.'],
        ['subjective', 'adj', '주관적인', 'Taste in music is very *subjective*.', '음악 취향은 매우 주관적이다.'],
        ['generalize', 'v', '일반화하다', "You shouldn't *generalize* from one example.", '한 가지 사례로 일반화해서는 안 된다.'],
        ['distort', 'v', '왜곡하다', 'The report seemed to *distort* the facts.', '그 보도는 사실을 왜곡하는 것처럼 보였다.'],
      ] },
      { name: '데이터와 보안', words: [
        ['encrypt', 'v', '암호화하다', 'The app will *encrypt* your messages.', '그 앱은 당신의 메시지를 암호화할 것이다.'],
        ['breach', 'n', '침해, 위반', 'The company suffered a data *breach*.', '그 회사는 데이터 유출을 겪었다.'],
        ['firewall', 'n', '방화벽', 'A *firewall* blocks unwanted traffic.', '방화벽은 원치 않는 트래픽을 차단한다.'],
        ['backup', 'n', '백업', 'Always keep a *backup* of your files.', '항상 파일의 백업을 보관해라.'],
        ['algorithm', 'n', '알고리즘', 'The *algorithm* sorts data quickly.', '그 알고리즘은 데이터를 빠르게 정렬한다.'],
        ['authenticate', 'v', '인증하다', 'The system will *authenticate* your identity.', '그 시스템은 당신의 신원을 인증할 것이다.'],
        ['vulnerability', 'n', '취약점', 'Hackers found a *vulnerability* in the system.', '해커들은 그 시스템에서 취약점을 발견했다.'],
        ['anonymous', 'adj', '익명의', 'The donor wished to remain *anonymous*.', '그 기부자는 익명으로 남기를 원했다.'],
      ] },
      { name: '심리 치료와 정신건강', words: [
        ['therapy', 'n', '치료, 요법', 'She started *therapy* after the accident.', '그녀는 사고 이후 치료를 시작했다.'],
        ['counselor', 'n', '상담사', 'The school hired a new *counselor*.', '그 학교는 새 상담사를 고용했다.'],
        ['trauma', 'n', '트라우마, 정신적 충격', 'The event left a lasting *trauma*.', '그 사건은 지속적인 트라우마를 남겼다.'],
        ['depression', 'n', '우울증', '*Depression* affects millions of people.', '우울증은 수백만 명에게 영향을 미친다.'],
        ['anxiety', 'n', '불안(감)', 'Public speaking causes her great *anxiety*.', '대중 연설은 그녀에게 큰 불안감을 일으킨다.'],
        ['cope', 'v', '대처하다, 극복하다', 'He learned to *cope* with stress.', '그는 스트레스에 대처하는 법을 배웠다.'],
        ['resilience', 'n', '회복력, 탄력성', 'Her *resilience* helped her recover quickly.', '그녀의 회복력은 그녀가 빨리 회복하도록 도왔다.'],
        ['wellbeing', 'n', '행복, 안녕, 웰빙', 'Mental *wellbeing* is as important as physical health.', '정신적 웰빙은 신체 건강만큼 중요하다.'],
      ] },
      { name: '국제무역과 글로벌경제', words: [
        ['export', 'v', '수출하다', 'The country plans to *export* more rice this year.', '그 나라는 올해 더 많은 쌀을 수출할 계획이다.'],
        ['import', 'v', '수입하다', 'We *import* coffee from Brazil.', '우리는 브라질에서 커피를 수입한다.'],
        ['tariff', 'n', '관세', 'The new *tariff* raised prices on cars.', '새 관세는 자동차 가격을 올렸다.'],
        ['globalization', 'n', '세계화', '*Globalization* connects economies worldwide.', '세계화는 전 세계의 경제를 연결한다.'],
        ['currency', 'n', '통화, 화폐', 'The dollar is a widely used *currency*.', '달러는 널리 사용되는 통화이다.'],
        ['exchange', 'n', '교환, 환전', 'Check the *exchange* rate before you travel.', '여행 전에 환율을 확인해라.'],
        ['outsource', 'v', '외주를 주다', 'The company decided to *outsource* production.', '그 회사는 생산을 외주로 주기로 했다.'],
        ['competitive', 'adj', '경쟁력 있는, 경쟁적인', 'They offer a *competitive* price.', '그들은 경쟁력 있는 가격을 제공한다.'],
      ] },
      { name: '통치체제와 정치사상', words: [
        ['parliament', 'n', '의회, 국회', '*Parliament* passed the new bill.', '의회는 새 법안을 통과시켰다.'],
        ['constitution', 'n', '헌법', 'The *constitution* protects basic rights.', '헌법은 기본권을 보호한다.'],
        ['authoritarian', 'adj', '권위주의적인', 'The regime became more *authoritarian*.', '그 정권은 더 권위주의적으로 변했다.'],
        ['monarchy', 'n', '군주제', 'The UK is a *monarchy*.', '영국은 군주제이다.'],
        ['candidate', 'n', '후보(자)', 'Each *candidate* gave a short speech.', '각 후보자는 짧은 연설을 했다.'],
        ['referendum', 'n', '국민투표', 'The country held a *referendum* on the issue.', '그 나라는 그 사안에 대해 국민투표를 실시했다.'],
        ['ideology', 'n', '이념, 이데올로기', 'The two parties follow a different *ideology*.', '두 정당은 서로 다른 이념을 따른다.'],
        ['autonomy', 'n', '자율성, 자치(권)', 'The region was granted more *autonomy*.', '그 지역은 더 많은 자치권을 부여받았다.'],
      ] },
      { name: '고급 부사와 연결어', words: [
        ['nevertheless', 'adv', '그럼에도 불구하고', 'It was raining; *nevertheless*, they went hiking.', '비가 오고 있었다; 그럼에도 불구하고 그들은 하이킹을 갔다.'],
        ['furthermore', 'adv', '게다가, 더욱이', 'The plan is expensive. *Furthermore*, it is risky.', '그 계획은 비용이 많이 든다. 게다가 위험하다.'],
        ['consequently', 'adv', '그 결과, 따라서', 'He missed the bus; *consequently*, he was late.', '그는 버스를 놓쳤다; 그 결과 그는 늦었다.'],
        ['inherently', 'adv', '본질적으로', 'The job is *inherently* dangerous.', '그 일은 본질적으로 위험하다.'],
        ['presumably', 'adv', '아마, 추측건대', '*Presumably*, he forgot about the meeting.', '아마 그는 그 회의를 잊었을 것이다.'],
        ['simultaneously', 'adv', '동시에', 'Both teams scored *simultaneously*.', '두 팀은 동시에 득점했다.'],
        ['arguably', 'adv', '거의 틀림없이, 주장하건대', 'She is *arguably* the best player on the team.', '그녀는 거의 틀림없이 그 팀 최고의 선수이다.'],
        ['ultimately', 'adv', '궁극적으로, 결국', '*Ultimately*, the decision is yours.', '궁극적으로 그 결정은 너의 몫이다.'],
      ] },
      { name: '인공지능과 로봇공학', words: [
        ['intelligence', 'n', '지능', '*Intelligence* can be measured in many ways.', '지능은 여러 방식으로 측정될 수 있다.'],
        ['automate', 'v', '자동화하다', 'Factories *automate* repetitive tasks.', '공장들은 반복적인 작업을 자동화한다.'],
        ['robotics', 'n', '로봇공학', 'He studies *robotics* in college.', '그는 대학에서 로봇공학을 공부한다.'],
        ['sensor', 'n', '센서, 감지기', 'The *sensor* detects motion in the room.', '그 센서는 방 안의 움직임을 감지한다.'],
        ['simulate', 'v', '모의 실험하다, 흉내 내다', 'The program can *simulate* real conditions.', '그 프로그램은 실제 조건을 모의 실험할 수 있다.'],
        ['autonomous', 'adj', '자율적인, 자율 주행의', 'The company tested an *autonomous* car.', '그 회사는 자율 주행 자동차를 시험했다.'],
        ['digital', 'adj', '디지털의', 'Most music is *digital* now.', '요즘 대부분의 음악은 디지털이다.'],
        ['interface', 'n', '인터페이스, 접점', 'The app has a simple *interface*.', '그 앱은 단순한 인터페이스를 가지고 있다.'],
      ] },
    ],
  },
];

export const POS_LABEL = { n: '명사', v: '동사', adj: '형용사', adv: '부사' };

export const LEVELS = RAW.map((lv) => ({
  id: lv.id,
  name: lv.name,
  icon: lv.icon,
  desc: lv.desc,
  stages: lv.stages.map((st, si) => ({
    key: `${lv.id}-${si + 1}`,
    level: lv.id,
    index: si,
    name: st.name,
    words: st.words.map(([en, pos, ko, ex, exKo]) => ({
      id: en, en, pos, ko, ex, exKo, level: lv.id, stage: `${lv.id}-${si + 1}`,
    })),
  })),
}));

export const ALL_WORDS = LEVELS.flatMap((lv) => lv.stages.flatMap((st) => st.words));
export const WORD_BY_ID = new Map(ALL_WORDS.map((w) => [w.id, w]));
export const STAGE_BY_KEY = new Map(LEVELS.flatMap((lv) => lv.stages.map((st) => [st.key, st])));

export const levelWords = (levelId) => ALL_WORDS.filter((w) => w.level === levelId);
