// 레벨 → 스테이지 → 단어 데이터.
// 단어 형식: [영단어, 품사(n/v/adj/adv), 뜻, 예문(대상 단어를 *...*로 감쌈), 예문 해석]
// 예문 속 *...*는 영단어와 똑같은 형태여야 합니다(빈칸 퀴즈가 이 표시를 이용). `node tests/test.mjs`로 검증됩니다.

const RAW = [
  {
    id: 1, name: '새싹', icon: '🌱', desc: '초등~중1 기초',
    stages: [
      { name: '일상 동사', words: [
        ['wake up', 'v', '일어나다', 'I *wake up* at seven every day.', '나는 매일 7시에 일어난다.'],
        ['borrow', 'v', '빌리다', 'Can I *borrow* your pen?', '펜 좀 빌려도 될까?'],
        ['carry', 'v', '나르다, 들고 다니다', 'Please *carry* this bag for me.', '이 가방 좀 들어 주세요.'],
        ['cook', 'v', '요리하다', 'My dad likes to *cook* on weekends.', '아빠는 주말에 요리하는 것을 좋아하신다.'],
        ['wash', 'v', '씻다', 'You should *wash* your hands before eating.', '먹기 전에 손을 씻어야 한다.'],
        ['leave', 'v', '떠나다', 'We *leave* for school at eight.', '우리는 8시에 학교로 출발한다.'],
        ['count', 'v', '세다', "Let's *count* from one to ten.", '1부터 10까지 세어 보자.'],
        ['wait', 'v', '기다리다', 'Please *wait* here for a moment.', '여기서 잠시만 기다려 주세요.'],
      ] },
      { name: '학교와 사물', words: [
        ['lesson', 'n', '수업, 교훈', "Today's *lesson* is about animals.", '오늘 수업은 동물에 관한 것이다.'],
        ['homework', 'n', '숙제', 'I finished my *homework* early.', '나는 숙제를 일찍 끝냈다.'],
        ['library', 'n', '도서관', 'She reads books in the *library*.', '그녀는 도서관에서 책을 읽는다.'],
        ['notebook', 'n', '공책', 'Write it in your *notebook*.', '그것을 공책에 적어라.'],
        ['subject', 'n', '과목, 주제', 'Math is my favorite *subject*.', '수학은 내가 가장 좋아하는 과목이다.'],
        ['desk', 'n', '책상', 'The books are on the *desk*.', '책들이 책상 위에 있다.'],
        ['exam', 'n', '시험', 'I have an *exam* tomorrow.', '나는 내일 시험이 있다.'],
        ['classmate', 'n', '반 친구', 'My *classmate* helped me with the project.', '반 친구가 프로젝트를 도와주었다.'],
      ] },
      { name: '음식과 장소', words: [
        ['delicious', 'adj', '맛있는', 'This soup is *delicious*.', '이 수프는 맛있다.'],
        ['hungry', 'adj', '배고픈', 'I am so *hungry* right now.', '나는 지금 너무 배가 고프다.'],
        ['bakery', 'n', '빵집', 'The *bakery* opens at six.', '그 빵집은 6시에 문을 연다.'],
        ['market', 'n', '시장', 'We buy fresh fruit at the *market*.', '우리는 시장에서 신선한 과일을 산다.'],
        ['restaurant', 'n', '식당', 'They ate dinner at a new *restaurant*.', '그들은 새 식당에서 저녁을 먹었다.'],
        ['drink', 'v', '마시다', 'You should *drink* more water.', '너는 물을 더 마셔야 한다.'],
        ['hospital', 'n', '병원', 'My aunt works at the *hospital*.', '이모는 병원에서 일하신다.'],
        ['station', 'n', '역', 'Meet me at the train *station*.', '기차역에서 만나자.'],
      ] },
      { name: '감정과 상태', words: [
        ['angry', 'adj', '화난', 'He was *angry* about the mistake.', '그는 그 실수에 화가 났다.'],
        ['proud', 'adj', '자랑스러운', 'I am *proud* of you.', '나는 네가 자랑스럽다.'],
        ['nervous', 'adj', '긴장한', 'She felt *nervous* before the speech.', '그녀는 연설 전에 긴장했다.'],
        ['lonely', 'adj', '외로운', 'He felt *lonely* in the new city.', '그는 새 도시에서 외로움을 느꼈다.'],
        ['surprised', 'adj', '놀란', 'We were *surprised* by the news.', '우리는 그 소식에 놀랐다.'],
        ['tired', 'adj', '피곤한', 'I was too *tired* to study.', '나는 너무 피곤해서 공부할 수 없었다.'],
        ['excited', 'adj', '신이 난', 'The kids are *excited* about the trip.', '아이들은 여행에 신이 나 있다.'],
        ['worry', 'v', '걱정하다', "Don't *worry* about the test.", '시험은 걱정하지 마.'],
      ] },
    ],
  },
  {
    id: 2, name: '새잎', icon: '🌿', desc: '중등 필수',
    stages: [
      { name: '생활 동사', words: [
        ['invite', 'v', '초대하다', 'I want to *invite* you to my party.', '너를 내 파티에 초대하고 싶어.'],
        ['improve', 'v', '향상시키다, 개선하다', 'Reading helps you *improve* your English.', '독서는 영어 실력을 향상시키는 데 도움이 된다.'],
        ['share', 'v', '나누다, 공유하다', 'Please *share* your ideas with the group.', '여러분의 생각을 모둠과 공유해 주세요.'],
        ['decide', 'v', '결정하다', 'It is hard to *decide* what to eat.', '무엇을 먹을지 결정하기가 어렵다.'],
        ['prepare', 'v', '준비하다', 'We need to *prepare* for the trip.', '우리는 여행을 준비해야 한다.'],
        ['repeat', 'v', '반복하다', 'Could you *repeat* that, please?', '다시 한번 말씀해 주시겠어요?'],
        ['mention', 'v', '언급하다', 'She did not *mention* the problem.', '그녀는 그 문제를 언급하지 않았다.'],
        ['protect', 'v', '보호하다', 'We must *protect* the environment.', '우리는 환경을 보호해야 한다.'],
      ] },
      { name: '사람과 관계', words: [
        ['neighbor', 'n', '이웃', 'Our *neighbor* is very kind.', '우리 이웃은 아주 친절하다.'],
        ['relative', 'n', '친척', 'I visit my *relative* in Busan every summer.', '나는 매년 여름 부산에 사는 친척을 방문한다.'],
        ['stranger', 'n', '낯선 사람', "Don't talk to a *stranger* online.", '온라인에서 낯선 사람과 이야기하지 마라.'],
        ['customer', 'n', '손님, 고객', 'The *customer* asked for a refund.', '그 고객은 환불을 요청했다.'],
        ['teenager', 'n', '십대', 'My brother is a *teenager* now.', '내 형은 이제 십대이다.'],
        ['citizen', 'n', '시민', 'Every *citizen* has the right to vote.', '모든 시민은 투표할 권리가 있다.'],
        ['volunteer', 'n', '자원봉사자', 'She works as a *volunteer* at the shelter.', '그녀는 보호소에서 자원봉사자로 일한다.'],
        ['partner', 'n', '짝, 파트너', 'Find a *partner* and practice speaking.', '짝을 찾아서 말하기를 연습해라.'],
      ] },
      { name: '자연과 날씨', words: [
        ['weather', 'n', '날씨', 'The *weather* is nice today.', '오늘은 날씨가 좋다.'],
        ['temperature', 'n', '온도, 기온', 'The *temperature* dropped at night.', '밤에 기온이 떨어졌다.'],
        ['storm', 'n', '폭풍', 'A big *storm* is coming tonight.', '오늘 밤 큰 폭풍이 온다.'],
        ['forest', 'n', '숲', 'We walked through the *forest*.', '우리는 숲속을 걸었다.'],
        ['island', 'n', '섬', 'They live on a small *island*.', '그들은 작은 섬에 산다.'],
        ['valley', 'n', '계곡, 골짜기', 'A river runs through the *valley*.', '강이 계곡을 가로질러 흐른다.'],
        ['flood', 'n', '홍수', 'The *flood* damaged many houses.', '홍수로 많은 집이 피해를 입었다.'],
        ['environment', 'n', '환경', 'Plastic is bad for the *environment*.', '플라스틱은 환경에 나쁘다.'],
      ] },
      { name: '형용사 모음', words: [
        ['ordinary', 'adj', '평범한', 'It was an *ordinary* day at school.', '학교에서의 평범한 하루였다.'],
        ['dangerous', 'adj', '위험한', 'Swimming here is *dangerous*.', '여기서 수영하는 것은 위험하다.'],
        ['familiar', 'adj', '익숙한', 'Her face looks *familiar*.', '그녀의 얼굴이 낯익다.'],
        ['terrible', 'adj', '끔찍한', 'I had a *terrible* headache.', '나는 끔찍한 두통이 있었다.'],
        ['honest', 'adj', '정직한', 'He is an *honest* person.', '그는 정직한 사람이다.'],
        ['flexible', 'adj', '유연한', 'My schedule is *flexible* this week.', '이번 주 내 일정은 유연하다.'],
        ['valuable', 'adj', '소중한, 가치 있는', 'Time is *valuable*.', '시간은 소중하다.'],
        ['cheerful', 'adj', '쾌활한', 'She is always *cheerful*.', '그녀는 늘 쾌활하다.'],
      ] },
    ],
  },
  {
    id: 3, name: '나무', icon: '🌳', desc: '고등 기초',
    stages: [
      { name: '학습과 사고', words: [
        ['concentrate', 'v', '집중하다', 'It is hard to *concentrate* in a noisy room.', '시끄러운 방에서는 집중하기 어렵다.'],
        ['memorize', 'v', '암기하다', 'I *memorize* ten words every day.', '나는 매일 단어 열 개를 암기한다.'],
        ['analyze', 'v', '분석하다', 'Scientists *analyze* the data carefully.', '과학자들은 자료를 꼼꼼히 분석한다.'],
        ['imagine', 'v', '상상하다', 'Can you *imagine* life without phones?', '휴대폰 없는 삶을 상상할 수 있니?'],
        ['curious', 'adj', '호기심 많은', 'Children are *curious* about everything.', '아이들은 모든 것에 호기심이 많다.'],
        ['assume', 'v', '가정하다, 추정하다', "Don't *assume* that everyone agrees.", '모두가 동의한다고 가정하지 마라.'],
        ['evidence', 'n', '증거', 'There is no *evidence* for that claim.', '그 주장에는 증거가 없다.'],
        ['conclude', 'v', '결론짓다', 'We can *conclude* that the plan works.', '우리는 그 계획이 효과가 있다고 결론지을 수 있다.'],
      ] },
      { name: '사회와 사건', words: [
        ['government', 'n', '정부', 'The *government* announced a new policy.', '정부는 새로운 정책을 발표했다.'],
        ['society', 'n', '사회', 'Technology has changed modern *society*.', '기술은 현대 사회를 변화시켰다.'],
        ['economy', 'n', '경제', 'The *economy* is growing slowly.', '경제가 느리게 성장하고 있다.'],
        ['crisis', 'n', '위기', 'The country faced a serious *crisis*.', '그 나라는 심각한 위기에 직면했다.'],
        ['democracy', 'n', '민주주의', 'Free speech is important in a *democracy*.', '민주주의에서는 표현의 자유가 중요하다.'],
        ['tradition', 'n', '전통', 'This festival is an old *tradition*.', '이 축제는 오래된 전통이다.'],
        ['opportunity', 'n', '기회', 'This job is a great *opportunity*.', '이 일자리는 좋은 기회이다.'],
        ['community', 'n', '지역 사회', 'The *community* raised money for the school.', '지역 사회가 학교를 위해 돈을 모았다.'],
      ] },
      { name: '변화와 결과', words: [
        ['increase', 'v', '증가하다', 'Prices *increase* every year.', '물가는 해마다 오른다.'],
        ['reduce', 'v', '줄이다', 'We should *reduce* waste.', '우리는 쓰레기를 줄여야 한다.'],
        ['achieve', 'v', '이루다, 달성하다', 'She worked hard to *achieve* her goal.', '그녀는 목표를 이루기 위해 열심히 노력했다.'],
        ['affect', 'v', '영향을 미치다', 'Sleep can *affect* your mood.', '수면은 기분에 영향을 미칠 수 있다.'],
        ['consequence', 'n', '결과', 'Every choice has a *consequence*.', '모든 선택에는 결과가 따른다.'],
        ['establish', 'v', '설립하다, 확립하다', 'They plan to *establish* a new school.', '그들은 새 학교를 설립할 계획이다.'],
        ['gradually', 'adv', '서서히', 'The weather *gradually* got warmer.', '날씨가 서서히 따뜻해졌다.'],
        ['threaten', 'v', '위협하다', 'Pollution can *threaten* wildlife.', '오염은 야생동물을 위협할 수 있다.'],
      ] },
      { name: '성격과 태도', words: [
        ['generous', 'adj', '너그러운, 후한', 'He is *generous* with his time.', '그는 자기 시간을 아낌없이 내준다.'],
        ['stubborn', 'adj', '고집 센', 'My little brother is very *stubborn*.', '내 동생은 매우 고집이 세다.'],
        ['reliable', 'adj', '믿을 수 있는', 'She is a *reliable* friend.', '그녀는 믿을 수 있는 친구이다.'],
        ['selfish', 'adj', '이기적인', 'It was *selfish* to take all the cake.', '케이크를 다 가져간 것은 이기적이었다.'],
        ['confident', 'adj', '자신감 있는', 'Be *confident* and speak clearly.', '자신감을 갖고 또렷하게 말해라.'],
        ['humble', 'adj', '겸손한', 'Despite his fame, he stays *humble*.', '유명하지만 그는 겸손함을 유지한다.'],
        ['cautious', 'adj', '조심스러운', 'Be *cautious* when you cross the road.', '길을 건널 때는 조심해라.'],
        ['ambitious', 'adj', '야심 찬', 'She is an *ambitious* young leader.', '그녀는 야심 찬 젊은 지도자이다.'],
      ] },
      { name: '과학과 기술', words: [
        ['experiment', 'n', '실험', 'Scientists conducted an *experiment* to test the theory.', '과학자들은 그 이론을 검증하기 위해 실험을 했다.'],
        ['invent', 'v', '발명하다', 'He wants to *invent* a new machine.', '그는 새로운 기계를 발명하고 싶어 한다.'],
        ['technology', 'n', '기술', 'New *technology* makes life easier.', '새로운 기술은 삶을 더 편리하게 만든다.'],
        ['device', 'n', '기기, 장치', 'This *device* can measure your heart rate.', '이 기기는 심박수를 측정할 수 있다.'],
        ['discover', 'v', '발견하다', 'Scientists *discover* new species every year.', '과학자들은 매년 새로운 종을 발견한다.'],
        ['laboratory', 'n', '실험실', 'She works in a chemistry *laboratory*.', '그녀는 화학 실험실에서 일한다.'],
        ['artificial', 'adj', '인공의', 'The lake has *artificial* lighting at night.', '그 호수는 밤에 인공 조명이 있다.'],
        ['innovative', 'adj', '혁신적인', 'The company released an *innovative* product.', '그 회사는 혁신적인 제품을 출시했다.'],
      ] },
      { name: '역사와 문화', words: [
        ['ancient', 'adj', '고대의', 'They found *ancient* coins in the field.', '그들은 들판에서 고대 동전을 발견했다.'],
        ['century', 'n', '세기', 'This castle was built in the 14th *century*.', '이 성은 14세기에 지어졌다.'],
        ['civilization', 'n', '문명', 'The Nile supported an early *civilization*.', '나일강은 초기 문명을 지탱했다.'],
        ['heritage', 'n', '유산, 문화재', 'This temple is a cultural *heritage* site.', '이 사원은 문화유산 지역이다.'],
        ['ritual', 'n', '의식, 의례', 'The tribe performs a special *ritual* every spring.', '그 부족은 매년 봄 특별한 의식을 치른다.'],
        ['myth', 'n', '신화', 'Greek *myth* tells the story of gods and heroes.', '그리스 신화는 신과 영웅들의 이야기를 전한다.'],
        ['explore', 'v', '탐험하다', 'Early sailors wanted to *explore* unknown oceans.', '초기 선원들은 미지의 바다를 탐험하고 싶어 했다.'],
        ['legacy', 'n', '업적, 유산', 'He left a great *legacy* for future generations.', '그는 후대를 위해 위대한 업적을 남겼다.'],
      ] },
      { name: '건강과 의학', words: [
        ['symptom', 'n', '증상', 'A high fever is a common *symptom* of flu.', '고열은 독감의 흔한 증상이다.'],
        ['treatment', 'n', '치료', 'The *treatment* lasted six weeks.', '그 치료는 6주 동안 계속되었다.'],
        ['diagnose', 'v', '진단하다', 'The doctor will *diagnose* the illness tomorrow.', '의사는 내일 그 병을 진단할 것이다.'],
        ['recover', 'v', '회복하다', 'It took months to *recover* from the surgery.', '수술에서 회복하는 데 몇 달이 걸렸다.'],
        ['nutrition', 'n', '영양', 'Good *nutrition* keeps your body strong.', '좋은 영양은 몸을 튼튼하게 유지해 준다.'],
        ['exhausted', 'adj', '기진맥진한', 'She felt *exhausted* after the marathon.', '그녀는 마라톤 후에 기진맥진했다.'],
        ['chronic', 'adj', '만성의', 'He suffers from a *chronic* back pain.', '그는 만성 요통을 앓고 있다.'],
        ['immune', 'adj', '면역의', 'Vitamin C can boost your *immune* system.', '비타민 C는 면역 체계를 강화할 수 있다.'],
      ] },
      { name: '법과 규범', words: [
        ['law', 'n', '법', 'Everyone must obey the *law*.', '모두가 법을 지켜야 한다.'],
        ['permission', 'n', '허가', 'You need *permission* to enter this room.', '이 방에 들어가려면 허가가 필요하다.'],
        ['violate', 'v', '위반하다', 'Drivers who *violate* the rule will be fined.', '규칙을 위반하는 운전자는 벌금을 물게 된다.'],
        ['punish', 'v', '처벌하다', 'The school will *punish* students who cheat.', '학교는 부정행위를 한 학생을 처벌할 것이다.'],
        ['legal', 'adj', '합법적인', 'Is it *legal* to park here?', '여기 주차하는 것이 합법인가요?'],
        ['illegal', 'adj', '불법적인', 'It is *illegal* to drive without a license.', '면허 없이 운전하는 것은 불법이다.'],
        ['regulation', 'n', '규정', 'The factory follows a strict safety *regulation*.', '그 공장은 엄격한 안전 규정을 따른다.'],
        ['violation', 'n', '위반', 'This is a clear *violation* of the rules.', '이것은 명백한 규칙 위반이다.'],
      ] },
      { name: '예술과 창작', words: [
        ['creative', 'adj', '창의적인', 'She has a very *creative* mind.', '그녀는 매우 창의적인 사고를 가지고 있다.'],
        ['inspire', 'v', '영감을 주다', 'Nature can *inspire* great artists.', '자연은 위대한 예술가들에게 영감을 줄 수 있다.'],
        ['masterpiece', 'n', '걸작', 'This novel is considered a *masterpiece*.', '이 소설은 걸작으로 여겨진다.'],
        ['sculpture', 'n', '조각품', 'The park has a famous bronze *sculpture*.', '그 공원에는 유명한 청동 조각품이 있다.'],
        ['exhibit', 'v', '전시하다', 'The museum will *exhibit* new paintings.', '그 박물관은 새 그림들을 전시할 것이다.'],
        ['melody', 'n', '선율, 멜로디', "I can't forget that beautiful *melody*.", '나는 그 아름다운 선율을 잊을 수 없다.'],
        ['imaginative', 'adj', '상상력이 풍부한', 'The children wrote an *imaginative* story.', '아이들은 상상력이 풍부한 이야기를 썼다.'],
        ['performance', 'n', '공연', 'The dance *performance* received great applause.', '그 무용 공연은 큰 박수를 받았다.'],
      ] },
    ],
  },
  {
    id: 4, name: '숲', icon: '🌲', desc: '수능·토익 필수',
    stages: [
      { name: '비즈니스', words: [
        ['schedule', 'n', '일정', 'Check the meeting *schedule*.', '회의 일정을 확인하세요.'],
        ['invoice', 'n', '청구서', 'Please send the *invoice* by Friday.', '금요일까지 청구서를 보내 주세요.'],
        ['negotiate', 'v', '협상하다', 'We will *negotiate* the price tomorrow.', '우리는 내일 가격을 협상할 것이다.'],
        ['deadline', 'n', '마감 기한', 'The *deadline* is next Monday.', '마감 기한은 다음 주 월요일이다.'],
        ['contract', 'n', '계약서', 'Both sides signed the *contract*.', '양측이 계약서에 서명했다.'],
        ['revenue', 'n', '수익, 매출', 'Company *revenue* rose by ten percent.', '회사 매출이 10퍼센트 올랐다.'],
        ['colleague', 'n', '동료', 'My *colleague* will cover for me.', '내 동료가 나 대신 맡아 줄 것이다.'],
        ['supervisor', 'n', '상사, 감독관', 'Ask your *supervisor* for approval.', '상사에게 승인을 요청하세요.'],
      ] },
      { name: '논리와 주장', words: [
        ['argue', 'v', '주장하다, 논쟁하다', 'Some experts *argue* that sleep is essential.', '일부 전문가들은 수면이 필수적이라고 주장한다.'],
        ['emphasize', 'v', '강조하다', 'Teachers often *emphasize* the importance of reading.', '교사들은 독서의 중요성을 자주 강조한다.'],
        ['contradict', 'v', '모순되다, 반박하다', 'His actions *contradict* his words.', '그의 행동은 그의 말과 모순된다.'],
        ['inevitable', 'adj', '불가피한', 'Change is *inevitable*.', '변화는 불가피하다.'],
        ['reluctant', 'adj', '꺼리는', 'He was *reluctant* to admit his mistake.', '그는 자신의 실수를 인정하기를 꺼렸다.'],
        ['controversial', 'adj', '논란이 많은', 'It is a *controversial* topic.', '그것은 논란이 많은 주제이다.'],
        ['justify', 'v', '정당화하다', 'Nothing can *justify* violence.', '어떤 것도 폭력을 정당화할 수 없다.'],
        ['implication', 'n', '함의, 영향', 'The *implication* of the study is serious.', '그 연구가 시사하는 바는 심각하다.'],
      ] },
      { name: '경제와 사회', words: [
        ['inflation', 'n', '물가 상승', 'High *inflation* hurts families.', '높은 물가 상승은 가계에 타격을 준다.'],
        ['budget', 'n', '예산', 'We need to stay within our *budget*.', '우리는 예산 안에서 지내야 한다.'],
        ['tax', 'n', '세금', 'You must pay income *tax*.', '소득세를 내야 한다.'],
        ['profit', 'n', '이익', 'The shop made a small *profit*.', '그 가게는 작은 이익을 냈다.'],
        ['unemployment', 'n', '실업', 'Youth *unemployment* is a serious problem.', '청년 실업은 심각한 문제이다.'],
        ['immigrant', 'n', '이민자', 'Each *immigrant* brings new ideas.', '이민자들은 저마다 새로운 아이디어를 가져온다.'],
        ['inequality', 'n', '불평등', 'Education can reduce *inequality*.', '교육은 불평등을 줄일 수 있다.'],
        ['subsidy', 'n', '보조금', 'Farmers receive a government *subsidy*.', '농부들은 정부 보조금을 받는다.'],
      ] },
      { name: '고난도 동사', words: [
        ['undermine', 'v', '약화시키다', 'Rumors can *undermine* trust.', '소문은 신뢰를 약화시킬 수 있다.'],
        ['enhance', 'v', '강화하다, 높이다', 'Music can *enhance* your memory.', '음악은 기억력을 높여 줄 수 있다.'],
        ['overcome', 'v', '극복하다', 'You can *overcome* any difficulty.', '너는 어떤 어려움도 극복할 수 있다.'],
        ['adapt', 'v', '적응하다', 'Animals *adapt* to their surroundings.', '동물들은 주변 환경에 적응한다.'],
        ['diminish', 'v', '줄어들다, 약해지다', 'Her fear began to *diminish*.', '그녀의 두려움이 줄어들기 시작했다.'],
        ['demonstrate', 'v', '입증하다, 보여주다', 'The experiment will *demonstrate* the idea.', '그 실험이 그 생각을 입증할 것이다.'],
        ['obtain', 'v', '얻다, 획득하다', 'You must *obtain* a permit first.', '먼저 허가증을 얻어야 한다.'],
        ['postpone', 'v', '연기하다', 'They had to *postpone* the game.', '그들은 경기를 연기해야 했다.'],
      ] },
      { name: '심리와 인지', words: [
        ['perceive', 'v', '인지하다, 지각하다', 'We *perceive* colors differently in dim light.', '우리는 어두운 빛 속에서 색깔을 다르게 지각한다.'],
        ['cognitive', 'adj', '인지의', 'The test measures *cognitive* ability.', '그 검사는 인지 능력을 측정한다.'],
        ['motivate', 'v', '동기를 부여하다', 'Good teachers *motivate* their students.', '좋은 교사는 학생들에게 동기를 부여한다.'],
        ['instinct', 'n', '본능', 'Animals rely on *instinct* to survive.', '동물들은 생존을 위해 본능에 의존한다.'],
        ['subconscious', 'adj', '잠재의식의', 'Our *subconscious* mind affects our choices.', '우리의 잠재의식은 선택에 영향을 미친다.'],
        ['perception', 'n', '인식, 지각', 'Public *perception* of the issue has changed.', '그 사안에 대한 대중의 인식이 변했다.'],
        ['rational', 'adj', '이성적인, 합리적인', 'Try to make a *rational* decision.', '이성적인 결정을 내리려고 노력해라.'],
        ['intuition', 'n', '직관', 'She trusted her *intuition* and left early.', '그녀는 직관을 믿고 일찍 떠났다.'],
      ] },
      { name: '환경과 지속가능성', words: [
        ['sustainable', 'adj', '지속 가능한', 'We need *sustainable* energy sources.', '우리는 지속 가능한 에너지원이 필요하다.'],
        ['emission', 'n', '배출(물)', 'The new law will cut carbon *emission*.', '새 법은 탄소 배출을 줄일 것이다.'],
        ['renewable', 'adj', '재생 가능한', 'Solar power is a *renewable* resource.', '태양광은 재생 가능한 자원이다.'],
        ['conserve', 'v', '보존하다, 아끼다', 'We should *conserve* water during the drought.', '가뭄 동안 우리는 물을 아껴야 한다.'],
        ['ecosystem', 'n', '생태계', 'Pollution can destroy an entire *ecosystem*.', '오염은 생태계 전체를 파괴할 수 있다.'],
        ['extinct', 'adj', '멸종된', 'The dodo bird became *extinct* long ago.', '도도새는 오래전에 멸종되었다.'],
        ['deforestation', 'n', '삼림 벌채', '*Deforestation* is a major cause of climate change.', '삼림 벌채는 기후 변화의 주요 원인이다.'],
        ['pollutant', 'n', '오염 물질', 'Factories release a harmful *pollutant* into the river.', '공장들은 강에 해로운 오염 물질을 배출한다.'],
      ] },
      { name: '국제 관계', words: [
        ['diplomat', 'n', '외교관', 'The *diplomat* met with foreign leaders.', '그 외교관은 외국 지도자들을 만났다.'],
        ['treaty', 'n', '조약', 'The two countries signed a peace *treaty*.', '두 나라는 평화 조약에 서명했다.'],
        ['alliance', 'n', '동맹', 'The nations formed a military *alliance*.', '그 국가들은 군사 동맹을 맺었다.'],
        ['sovereignty', 'n', '주권', 'The country fought to protect its *sovereignty*.', '그 나라는 주권을 지키기 위해 싸웠다.'],
        ['refugee', 'n', '난민', 'The camp provides shelter for every *refugee*.', '그 수용소는 모든 난민에게 쉼터를 제공한다.'],
        ['embassy', 'n', '대사관', 'She works at the Korean *embassy* in Paris.', '그녀는 파리에 있는 한국 대사관에서 일한다.'],
        ['diplomatic', 'adj', '외교의, 외교적인', 'They tried to find a *diplomatic* solution.', '그들은 외교적인 해결책을 찾으려 했다.'],
        ['negotiation', 'n', '협상', 'The *negotiation* lasted for three days.', '그 협상은 사흘 동안 계속되었다.'],
      ] },
      { name: '고급 형용사', words: [
        ['subtle', 'adj', '미묘한', 'There is a *subtle* difference between the two colors.', '그 두 색깔 사이에는 미묘한 차이가 있다.'],
        ['ambiguous', 'adj', '모호한', 'His answer was *ambiguous* and confusing.', '그의 대답은 모호하고 혼란스러웠다.'],
        ['profound', 'adj', '깊은, 심오한', 'The book had a *profound* effect on me.', '그 책은 나에게 깊은 영향을 미쳤다.'],
        ['versatile', 'adj', '다재다능한, 다용도의', 'She is a *versatile* actress.', '그녀는 다재다능한 배우이다.'],
        ['meticulous', 'adj', '꼼꼼한, 세심한', 'He is *meticulous* about every detail.', '그는 모든 세부 사항에 꼼꼼하다.'],
        ['tedious', 'adj', '지루한, 따분한', 'Filling out forms can be *tedious*.', '양식을 작성하는 것은 지루할 수 있다.'],
        ['plausible', 'adj', '그럴듯한, 타당한', 'Her explanation sounded *plausible*.', '그녀의 설명은 그럴듯하게 들렸다.'],
        ['redundant', 'adj', '불필요한, 중복된', 'Some of the words in the essay are *redundant*.', '그 에세이의 일부 단어는 불필요하다.'],
      ] },
      { name: '학술 명사', words: [
        ['hypothesis', 'n', '가설', 'The scientist tested her *hypothesis*.', '그 과학자는 자신의 가설을 검증했다.'],
        ['methodology', 'n', '방법론', 'The report explains the research *methodology*.', '그 보고서는 연구 방법론을 설명한다.'],
        ['variable', 'n', '변수', 'Temperature is an important *variable* in the experiment.', '온도는 그 실험에서 중요한 변수이다.'],
        ['correlation', 'n', '상관관계', 'There is a strong *correlation* between sleep and health.', '수면과 건강 사이에는 강한 상관관계가 있다.'],
        ['criteria', 'n', '기준(들)', 'The judges use strict *criteria* to score the contest.', '심사위원들은 엄격한 기준으로 대회 점수를 매긴다.'],
        ['phenomenon', 'n', '현상', 'Global warming is a well-known *phenomenon*.', '지구 온난화는 잘 알려진 현상이다.'],
        ['statistics', 'n', '통계', 'The *statistics* show a clear trend.', '그 통계는 분명한 추세를 보여준다.'],
        ['theoretical', 'adj', '이론적인', 'This is a *theoretical* model, not a real one.', '이것은 실제가 아니라 이론적인 모델이다.'],
      ] },
    ],
  },
];

export const POS_LABEL = { n: '명사', v: '동사', adj: '형용사', adv: '부사' };

export const LEVELS = RAW.map((lv) => ({
  id: lv.id,
  name: lv.name,
  icon: lv.icon,
  desc: lv.desc,
  stages: lv.stages.map((st, si) => ({
    key: `${lv.id}-${si + 1}`,
    level: lv.id,
    index: si,
    name: st.name,
    words: st.words.map(([en, pos, ko, ex, exKo]) => ({
      id: en, en, pos, ko, ex, exKo, level: lv.id, stage: `${lv.id}-${si + 1}`,
    })),
  })),
}));

export const ALL_WORDS = LEVELS.flatMap((lv) => lv.stages.flatMap((st) => st.words));
export const WORD_BY_ID = new Map(ALL_WORDS.map((w) => [w.id, w]));
export const STAGE_BY_KEY = new Map(LEVELS.flatMap((lv) => lv.stages.map((st) => [st.key, st])));

export const levelWords = (levelId) => ALL_WORDS.filter((w) => w.level === levelId);
